// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type CreateOpenIdSessionControllerRunData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/openid/session';
};

export type CreateOpenIdSessionControllerRunResponses = {
    201: {
        jwt: string;
    };
};

export type CreateOpenIdSessionControllerRunResponse = CreateOpenIdSessionControllerRunResponses[keyof CreateOpenIdSessionControllerRunResponses];

export type CreateOpenIdSessionWithLegalTextsControllerRunData = {
    body: {
        legalTextLanguage: 'en_GB' | 'es_ES';
        acceptServiceTermId?: string;
        acceptPrivacyPolicyId?: string;
    };
    path?: never;
    query?: never;
    url: '/openid/session-with-legal-texts';
};

export type CreateOpenIdSessionWithLegalTextsControllerRunResponses = {
    201: {
        jwt: string;
    };
};

export type CreateOpenIdSessionWithLegalTextsControllerRunResponse = CreateOpenIdSessionWithLegalTextsControllerRunResponses[keyof CreateOpenIdSessionWithLegalTextsControllerRunResponses];

export type CreatePasswordTokenControllerRunData = {
    body: {
        email: string;
        recoveredFrom: 'Web' | 'AppPro' | 'AppLite';
    };
    path?: never;
    query?: never;
    url: '/recover-password';
};

export type CreatePasswordTokenControllerRunResponses = {
    201: unknown;
};

export type DeleteSessionControllerRunData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/session';
};

export type DeleteSessionControllerRunResponses = {
    204: void;
};

export type DeleteSessionControllerRunResponse = DeleteSessionControllerRunResponses[keyof DeleteSessionControllerRunResponses];

export type CreateSessionControllerRunData = {
    body?: unknown;
    path?: never;
    query?: never;
    url: '/session';
};

export type CreateSessionControllerRunResponses = {
    201: {
        jwt: string;
    };
};

export type CreateSessionControllerRunResponse = CreateSessionControllerRunResponses[keyof CreateSessionControllerRunResponses];

export type CreateSessionWithLegalTextsControllerRunData = {
    body: {
        email: string;
        password: string;
        legalTextLanguage: 'en_GB' | 'es_ES';
        acceptServiceTermId?: string;
        acceptPrivacyPolicyId?: string;
    };
    path?: never;
    query?: never;
    url: '/session-with-legal-texts';
};

export type CreateSessionWithLegalTextsControllerRunResponses = {
    201: {
        jwt: string;
    };
};

export type CreateSessionWithLegalTextsControllerRunResponse = CreateSessionWithLegalTextsControllerRunResponses[keyof CreateSessionWithLegalTextsControllerRunResponses];

export type ShowOpenIdUserInfoControllerRunData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/openid/user-info';
};

export type ShowOpenIdUserInfoControllerRunResponses = {
    200: {
        firstName: string;
        lastName: string;
        companyId: string;
        email: string;
    };
};

export type ShowOpenIdUserInfoControllerRunResponse = ShowOpenIdUserInfoControllerRunResponses[keyof ShowOpenIdUserInfoControllerRunResponses];

export type ShowSessionInfoControllerRunData = {
    body?: never;
    path: {
        email: string;
    };
    query?: never;
    url: '/session-info/{email}';
};

export type ShowSessionInfoControllerRunResponses = {
    200: {
        type: 'Password' | 'OpenId';
        issuer?: string;
        clientId?: string;
        scope?: Array<string>;
    };
};

export type ShowSessionInfoControllerRunResponse = ShowSessionInfoControllerRunResponses[keyof ShowSessionInfoControllerRunResponses];

export type UpdatePasswordWithPasswordTokenControllerRunData = {
    body: {
        password: string;
        passwordConfirmation: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/recover-password/{id}';
};

export type UpdatePasswordWithPasswordTokenControllerRunResponses = {
    204: void;
};

export type UpdatePasswordWithPasswordTokenControllerRunResponse = UpdatePasswordWithPasswordTokenControllerRunResponses[keyof UpdatePasswordWithPasswordTokenControllerRunResponses];

export type CreateCaseFileControllerRunData = {
    body: {
        id: string;
        name: string;
        reference?: string;
        description?: string;
        useCaseId: string;
    };
    path?: never;
    query?: never;
    url: '/case-files';
};

export type CreateCaseFileControllerRunResponses = {
    201: unknown;
};

export type CreateCaseFilesSharingControllerRunData = {
    body: {
        userIds: Array<string>;
        role: 'COLLABORATOR' | 'EDITOR' | 'MANAGER';
    };
    path: {
        caseFileId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/sharing';
};

export type CreateCaseFilesSharingControllerRunResponses = {
    201: unknown;
};

export type DeleteCaseFilesSharingControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        id: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/sharing/{id}';
};

export type DeleteCaseFilesSharingControllerRunResponses = {
    204: void;
};

export type DeleteCaseFilesSharingControllerRunResponse = DeleteCaseFilesSharingControllerRunResponses[keyof DeleteCaseFilesSharingControllerRunResponses];

export type UpdateCaseFilesSharingControllerRunData = {
    body: {
        role?: 'COLLABORATOR' | 'EDITOR' | 'MANAGER';
    };
    path: {
        caseFileId: string;
        id: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/sharing/{id}';
};

export type UpdateCaseFilesSharingControllerRunResponses = {
    204: void;
};

export type UpdateCaseFilesSharingControllerRunResponse = UpdateCaseFilesSharingControllerRunResponses[keyof UpdateCaseFilesSharingControllerRunResponses];

export type ListCaseFilesControllerRunData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: {
        filter?: {
            search?: string;
            status?: 'OPEN' | 'CLOSED';
            statuses?: Array<'OPEN' | 'CLOSED'>;
            createdById?: string;
            ownerId?: string;
            ownerOrSharedWithId?: string;
            useCaseId?: string;
            id?: string;
        };
        order?: {
            createdAt?: 'ASC' | 'DESC';
        };
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/users/{userId}/case-files';
};

export type ListCaseFilesControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            code: string;
            name: string;
            useCaseId: string;
            createdAt: string;
            status: string;
            owner: {
                id: string;
                firstName: string;
                lastName: string;
            };
            createdBy?: {
                id: string;
                firstName: string;
                lastName: string;
            };
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListCaseFilesControllerRunResponse = ListCaseFilesControllerRunResponses[keyof ListCaseFilesControllerRunResponses];

export type ListCaseFilesSharingControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
    };
    query?: {
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/case-files/{caseFileId}/sharing-with-users';
};

export type ListCaseFilesSharingControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            caseFileId: string;
            userId: string;
            role: string;
            user: {
                role: string;
                firstName: string;
                lastName: string;
                email: string;
            };
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListCaseFilesSharingControllerRunResponse = ListCaseFilesSharingControllerRunResponses[keyof ListCaseFilesSharingControllerRunResponses];

export type ShowCaseFileControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}';
};

export type ShowCaseFileControllerRunResponses = {
    200: {
        id: string;
        code: string;
        name: string;
        useCaseId: string;
        createdAt: string;
        status: string;
        owner: {
            id: string;
            firstName: string;
            lastName: string;
        };
        createdBy?: {
            id: string;
            firstName: string;
            lastName: string;
        };
    };
};

export type ShowCaseFileControllerRunResponse = ShowCaseFileControllerRunResponses[keyof ShowCaseFileControllerRunResponses];

export type UpdateCaseFileControllerRunData = {
    body: {
        status?: 'OPEN' | 'CLOSED';
        name?: string;
        reference?: string;
        description?: string;
    };
    path: {
        caseFileId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}';
};

export type UpdateCaseFileControllerRunResponses = {
    204: void;
};

export type UpdateCaseFileControllerRunResponse = UpdateCaseFileControllerRunResponses[keyof UpdateCaseFileControllerRunResponses];

export type ShowCaseFilesSharingControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/my-sharing-role';
};

export type ShowCaseFilesSharingControllerRunResponses = {
    200: {
        id: string;
        caseFileId: string;
        userId: string;
        role: string;
    };
};

export type ShowCaseFilesSharingControllerRunResponse = ShowCaseFilesSharingControllerRunResponses[keyof ShowCaseFilesSharingControllerRunResponses];

export type CertifyDossierControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        dossierId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/dossiers/{dossierId}/certify';
};

export type CertifyDossierControllerRunResponses = {
    202: unknown;
};

export type ListDossiersControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
    };
    query?: {
        filter?: {
            caseFileId?: string;
            search?: string;
            createdFrom?: string;
            createdUntil?: string;
            status?: 'CERTIFYING' | 'DRAFT' | 'CERTIFIED';
            statuses?: Array<'CERTIFYING' | 'DRAFT' | 'CERTIFIED'>;
            createdById?: string;
            ownerIds?: Array<string>;
            id?: string;
        };
        order?: {
            createdAt?: 'ASC' | 'DESC';
        };
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/case-files/{caseFileId}/dossiers';
};

export type ListDossiersControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            caseFileId: string;
            code: string;
            name: string;
            status: string;
            createdAt: string;
            certifiedAt?: string;
            evidencesCount: number;
            evidenceGroupsCount: number;
            visibility: string;
            owner: {
                id: string;
                firstName: string;
                lastName: string;
            };
            createdBy?: {
                id: string;
                firstName: string;
                lastName: string;
            };
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListDossiersControllerRunResponse = ListDossiersControllerRunResponses[keyof ListDossiersControllerRunResponses];

export type CreateDossierControllerRunData = {
    body: {
        /**
         * @deprecated
         */
        dossierTemplateId?: string;
        /**
         * @deprecated
         */
        purpose?: string;
        id: string;
        modelId?: string;
        name: string;
        language: 'en_GB' | 'es_ES' | 'pt_PT';
        filledFields?: {
            [key: string]: unknown;
        };
        validityFrom: string;
        validityTo: string;
        accessToken?: string;
    };
    path: {
        caseFileId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/dossiers';
};

export type CreateDossierControllerRunResponses = {
    201: unknown;
};

export type CreateDossierExpressControllerRunData = {
    body: {
        id: string;
        modelId?: string;
        evidenceIds?: Array<string>;
        name: string;
        language: 'en_GB' | 'es_ES' | 'pt_PT';
    };
    path: {
        caseFileId: string;
        evidenceGroupId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/dossier-express';
};

export type CreateDossierExpressControllerRunResponses = {
    201: unknown;
};

export type DeleteDossierControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        dossierId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/dossiers/{dossierId}';
};

export type DeleteDossierControllerRunResponses = {
    204: void;
};

export type DeleteDossierControllerRunResponse = DeleteDossierControllerRunResponses[keyof DeleteDossierControllerRunResponses];

export type ShowDossierControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        dossierId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/dossiers/{dossierId}';
};

export type ShowDossierControllerRunResponses = {
    200: {
        /**
         * @deprecated
         */
        dossierTemplateId: string;
        /**
         * @deprecated
         */
        purpose?: string;
        /**
         * @deprecated
         */
        dossierTemplateFilename?: string;
        id: string;
        modelId: string;
        code: string;
        name: string;
        language: string;
        filledFields: {
            [key: string]: unknown;
        };
        status: string;
        visibility: string;
        caseFileId: string;
        createdAt: string;
        evidencesCount: number;
        evidenceGroupsCount: number;
        certifiedAt?: string;
        owner: {
            id: string;
            firstName: string;
            lastName: string;
        };
        createdBy?: {
            id: string;
            firstName: string;
            lastName: string;
        };
        accessToken?: string;
    };
};

export type ShowDossierControllerRunResponse = ShowDossierControllerRunResponses[keyof ShowDossierControllerRunResponses];

export type UpdateDossierControllerRunData = {
    body: {
        /**
         * @deprecated
         */
        dossierTemplateId?: string;
        /**
         * @deprecated
         */
        purpose?: string;
        modelId?: string;
        name?: string;
        language?: 'en_GB' | 'es_ES' | 'pt_PT';
        filledFields?: {
            [key: string]: unknown;
        };
        validityFrom?: string;
        validityTo?: string;
        accessToken?: string;
    };
    path: {
        caseFileId: string;
        dossierId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/dossiers/{dossierId}';
};

export type UpdateDossierControllerRunResponses = {
    204: void;
};

export type UpdateDossierControllerRunResponse = UpdateDossierControllerRunResponses[keyof UpdateDossierControllerRunResponses];

export type ListDossierRecallRequestsControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        dossierId: string;
    };
    query?: {
        filter?: {
            id?: string;
            email?: string;
            resolved?: boolean;
        };
        order?: {
            createdAt?: 'ASC' | 'DESC';
        };
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/case-files/{caseFileId}/dossiers/{dossierId}/recall-requests';
};

export type ListDossierRecallRequestsControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            dossierId: string;
            firstName: string;
            lastName: string;
            phoneNumber?: string;
            email: string;
            reason: string;
            createdAt: string;
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListDossierRecallRequestsControllerRunResponse = ListDossierRecallRequestsControllerRunResponses[keyof ListDossierRecallRequestsControllerRunResponses];

export type ShowDossierDocumentUrlControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        dossierId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/dossiers/{dossierId}/document-url';
};

export type ShowDossierDocumentUrlControllerRunResponses = {
    200: {
        documentUrl: string;
    };
};

export type ShowDossierDocumentUrlControllerRunResponse = ShowDossierDocumentUrlControllerRunResponses[keyof ShowDossierDocumentUrlControllerRunResponses];

export type ShowDossierPackageUrlControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        dossierId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/dossiers/{dossierId}/package-url';
};

export type ShowDossierPackageUrlControllerRunResponses = {
    200: {
        packageUrl: string;
    };
};

export type ShowDossierPackageUrlControllerRunResponse = ShowDossierPackageUrlControllerRunResponses[keyof ShowDossierPackageUrlControllerRunResponses];

export type ShowDossierPreviewControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        dossierId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/dossiers/{dossierId}/report-preview';
};

export type ShowDossierPreviewControllerRunResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type ShowDossierPreviewControllerRunResponse = ShowDossierPreviewControllerRunResponses[keyof ShowDossierPreviewControllerRunResponses];

export type ShowEvidenceWithLinkedToDossiersControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        evidenceGroupId: string;
        id: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/evidences-with-linked-to-dossiers/{id}';
};

export type ShowEvidenceWithLinkedToDossiersControllerRunResponses = {
    200: {
        id: string;
        linkedToDossiers: boolean;
    };
};

export type ShowEvidenceWithLinkedToDossiersControllerRunResponse = ShowEvidenceWithLinkedToDossiersControllerRunResponses[keyof ShowEvidenceWithLinkedToDossiersControllerRunResponses];

export type UpdateDossierVisibilityControllerRunData = {
    body: {
        visibility: 'ACCESSIBLE' | 'PENDING_RECALL' | 'RECALLED';
    };
    path: {
        caseFileId: string;
        dossierId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/dossiers/{dossierId}/visibility';
};

export type UpdateDossierVisibilityControllerRunResponses = {
    204: void;
};

export type UpdateDossierVisibilityControllerRunResponse = UpdateDossierVisibilityControllerRunResponses[keyof UpdateDossierVisibilityControllerRunResponses];

export type ListDossierTemplatesControllerRunData = {
    body?: never;
    path?: never;
    query?: {
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/dossier-templates';
};

export type ListDossierTemplatesControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            index: number;
            requiresPurpose: boolean;
            translations: Array<{
                id: string;
                name: string;
                language: string;
                tipsDescription: string;
                tipsList: Array<string>;
                purposeDossier: string;
            }>;
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListDossierTemplatesControllerRunResponse = ListDossierTemplatesControllerRunResponses[keyof ListDossierTemplatesControllerRunResponses];

export type CloseEvidenceGroupControllerRunData = {
    body: {
        evidencesCount: number;
        deviceModel?: string;
        deviceManufacturer?: string;
        deviceOS?: string;
        latitudeLocation?: string;
        longitudeLocation?: string;
        altitudeLocation?: string;
        locationAccuracy?: string;
        userAgent?: string;
        webUrl?: string;
        attestation?: {
            provider: 'PlayIntegrity' | 'AppAttest';
            app: 'App' | 'AppPro';
            token?: string;
            keyId?: string;
            assertion?: string;
        };
    };
    path: {
        caseFileId: string;
        id: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/evidence-groups/{id}/close';
};

export type CloseEvidenceGroupControllerRunResponses = {
    202: unknown;
};

export type CreateEvidenceControllerRunData = {
    body: {
        id: string;
        hash: string;
        title: string;
        evidenceGroupId: string;
        caseFileId: string;
        custodyType: 'INTERNAL' | 'EXTERNAL';
        fileName?: string;
    };
    path?: never;
    query?: never;
    url: '/evidences';
};

export type CreateEvidenceControllerRunResponses = {
    202: {
        uploadFileUrl?: string;
        expiration?: string;
    };
};

export type CreateEvidenceControllerRunResponse = CreateEvidenceControllerRunResponses[keyof CreateEvidenceControllerRunResponses];

export type CreateEvidenceGroupControllerRunData = {
    body: {
        id: string;
        evidenceType: 'FILE' | 'PHOTO' | 'VIDEO' | 'WEB_PLUGIN';
        name: string;
        description?: string;
        caseFileId: string;
        attestation?: {
            provider: 'PlayIntegrity' | 'AppAttest';
            app: 'App' | 'AppPro';
            token?: string;
            keyId?: string;
            assertion?: string;
        };
    };
    path?: never;
    query?: never;
    url: '/evidence-groups';
};

export type CreateEvidenceGroupControllerRunResponses = {
    201: unknown;
};

export type DeleteEvidenceControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        evidenceGroupId: string;
        id: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/evidences/{id}';
};

export type DeleteEvidenceControllerRunResponses = {
    204: void;
};

export type DeleteEvidenceControllerRunResponse = DeleteEvidenceControllerRunResponses[keyof DeleteEvidenceControllerRunResponses];

export type ShowEvidenceControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        evidenceGroupId: string;
        id: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/evidences/{id}';
};

export type ShowEvidenceControllerRunResponses = {
    200: {
        /**
         * @deprecated
         */
        tspTimestamp?: {
            provider: string;
            token: string;
            date: string;
        };
        /**
         * @deprecated
         */
        dltTimestamp?: {
            provider: string;
            blockExplorerLink: string;
            date: string;
        };
        id: string;
        title?: string;
        fileSize?: number;
        fileName: string;
        capturedAt: string;
        status: string;
        hash: string;
        relevant: boolean;
        favorite: boolean;
        custodyType: string;
        tspTimestamps: Array<{
            provider: string;
            token: string;
            date: string;
        }>;
        dltTimestamps: Array<{
            provider: string;
            blockExplorerLink: string;
            date: string;
        }>;
    };
};

export type ShowEvidenceControllerRunResponse = ShowEvidenceControllerRunResponses[keyof ShowEvidenceControllerRunResponses];

export type UpdateEvidenceControllerRunData = {
    body: {
        title?: string;
        relevant?: boolean;
    };
    path: {
        evidenceGroupId: string;
        caseFileId: string;
        id: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/evidences/{id}';
};

export type UpdateEvidenceControllerRunResponses = {
    204: void;
};

export type UpdateEvidenceControllerRunResponse = UpdateEvidenceControllerRunResponses[keyof UpdateEvidenceControllerRunResponses];

export type DiscardEvidenceGroupControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        id: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/evidence-groups/{id}';
};

export type DiscardEvidenceGroupControllerRunResponses = {
    204: void;
};

export type DiscardEvidenceGroupControllerRunResponse = DiscardEvidenceGroupControllerRunResponses[keyof DiscardEvidenceGroupControllerRunResponses];

export type ShowEvidenceGroupControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        id: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/evidence-groups/{id}';
};

export type ShowEvidenceGroupControllerRunResponses = {
    200: {
        id: string;
        caseFileId: string;
        code: string;
        name: string;
        description?: string;
        type: string;
        status: string;
        evidenceStats: {
            inProcess: number;
            failed: number;
            completed: number;
            total: number;
        };
        evidenceMetadataId?: string;
        createdBy?: {
            id: string;
            firstName: string;
            lastName: string;
        };
        createdAt: string;
    };
};

export type ShowEvidenceGroupControllerRunResponse = ShowEvidenceGroupControllerRunResponses[keyof ShowEvidenceGroupControllerRunResponses];

export type UpdateEvidenceGroupControllerRunData = {
    body: {
        name: string;
        description?: string;
    };
    path: {
        caseFileId: string;
        id: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/evidence-groups/{id}';
};

export type UpdateEvidenceGroupControllerRunResponses = {
    204: void;
};

export type UpdateEvidenceGroupControllerRunResponse = UpdateEvidenceGroupControllerRunResponses[keyof UpdateEvidenceGroupControllerRunResponses];

export type DownloadUrlEvidenceControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        evidenceGroupId: string;
        id: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/evidences/{id}/download-url';
};

export type DownloadUrlEvidenceControllerRunResponses = {
    200: {
        downloadFileUrl: string;
    };
};

export type DownloadUrlEvidenceControllerRunResponse = DownloadUrlEvidenceControllerRunResponses[keyof DownloadUrlEvidenceControllerRunResponses];

export type ListEvidenceGroupsControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
    };
    query?: {
        filter?: {
            ids?: Array<string>;
            caseFileId?: string;
            createdById?: string;
            name?: string;
            createdFrom?: string;
            createdUntil?: string;
            status?: 'OPEN' | 'CLOSED' | 'CLOSING';
            type?: 'FILE' | 'PHOTO' | 'VIDEO' | 'WEB_PLUGIN';
            id?: string;
        };
        order?: {
            createdAt?: 'ASC' | 'DESC';
        };
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/case-files/{caseFileId}/evidence-groups';
};

export type ListEvidenceGroupsControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            caseFileId: string;
            code: string;
            name: string;
            type: string;
            status: string;
            evidenceStats: {
                inProcess: number;
                failed: number;
                completed: number;
                total: number;
            };
            createdBy?: {
                id: string;
                firstName: string;
                lastName: string;
            };
            createdAt: string;
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListEvidenceGroupsControllerRunResponse = ListEvidenceGroupsControllerRunResponses[keyof ListEvidenceGroupsControllerRunResponses];

export type ListEvidencesByCaseFileControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
    };
    query?: {
        filter?: {
            ids?: Array<string>;
            caseFileId?: string;
            evidenceGroupIds?: Array<string>;
            evidenceGroupTypes?: Array<'FILE' | 'PHOTO' | 'VIDEO' | 'WEB_PLUGIN'>;
            title?: string;
            status?: 'COMPLETED' | 'IN_PROCESS' | 'ERROR';
            capturedFrom?: string;
            capturedUntil?: string;
            relevant?: boolean;
            favorite?: boolean;
            collectionMetadata?: boolean;
            id?: string;
        };
        order?: {
            capturedAt?: 'ASC' | 'DESC';
            evidenceGroupName?: 'ASC' | 'DESC';
        };
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/case-files/{caseFileId}/evidences';
};

export type ListEvidencesByCaseFileControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            title?: string;
            fileSize?: number;
            fileName: string;
            capturedAt: string;
            status: string;
            hash: string;
            relevant: boolean;
            favorite: boolean;
            custodyType: string;
            evidenceGroup: {
                id: string;
                code: string;
                name: string;
                type: string;
            };
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListEvidencesByCaseFileControllerRunResponse = ListEvidencesByCaseFileControllerRunResponses[keyof ListEvidencesByCaseFileControllerRunResponses];

export type ListEvidencesControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        evidenceGroupId: string;
    };
    query?: {
        filter?: {
            ids?: Array<string>;
            caseFileId?: string;
            evidenceGroupIds?: Array<string>;
            evidenceGroupTypes?: Array<'FILE' | 'PHOTO' | 'VIDEO' | 'WEB_PLUGIN'>;
            title?: string;
            status?: 'COMPLETED' | 'IN_PROCESS' | 'ERROR';
            capturedFrom?: string;
            capturedUntil?: string;
            relevant?: boolean;
            favorite?: boolean;
            collectionMetadata?: boolean;
            id?: string;
        };
        order?: {
            capturedAt?: 'ASC' | 'DESC';
            evidenceGroupName?: 'ASC' | 'DESC';
        };
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/evidences';
};

export type ListEvidencesControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            title?: string;
            fileSize?: number;
            fileName: string;
            capturedAt: string;
            status: string;
            hash: string;
            relevant: boolean;
            favorite: boolean;
            custodyType: string;
            evidenceGroup: {
                id: string;
                code: string;
                name: string;
                type: string;
            };
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListEvidencesControllerRunResponse = ListEvidencesControllerRunResponses[keyof ListEvidencesControllerRunResponses];

export type ListEvidenceTypesControllerRunData = {
    body?: never;
    path?: never;
    query?: {
        filter?: {
            code?: 'FILE' | 'PHOTO' | 'VIDEO' | 'WEB_PLUGIN';
            id?: string;
        };
        order?: {
            createdAt?: 'ASC' | 'DESC';
            index?: 'ASC' | 'DESC';
        };
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/evidence-types';
};

export type ListEvidenceTypesControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            code: string;
            index: number;
            translations: Array<{
                id: string;
                name: string;
                language: string;
                tipsDescription: string;
                tipsList: Array<string>;
                purposeDossier: string;
            }>;
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListEvidenceTypesControllerRunResponse = ListEvidenceTypesControllerRunResponses[keyof ListEvidenceTypesControllerRunResponses];

export type ListTimestampTypesControllerRunData = {
    body?: never;
    path?: never;
    query?: {
        filter?: {
            id?: string;
        };
        order?: {
            createdAt?: 'ASC' | 'DESC';
            index?: 'ASC' | 'DESC';
        };
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/timestamp-types';
};

export type ListTimestampTypesControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            category: 'TSP' | 'DLT';
            index: number;
            translations: Array<{
                id: string;
                name: string;
                language: string;
                tipsDescription: string;
                tipsList: Array<string>;
                purposeDossier: string;
            }>;
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListTimestampTypesControllerRunResponse = ListTimestampTypesControllerRunResponses[keyof ListTimestampTypesControllerRunResponses];

export type ProcessEvidenceGroupsCallbackControllerRunData = {
    body: {
        operation: string;
        result: 'OK' | 'KO';
        data: {
            evidenceGroupId: string;
            caseFileId: string;
        };
    };
    path?: never;
    query?: never;
    url: '/evidence-groups/callback';
};

export type ProcessEvidenceGroupsCallbackControllerRunResponses = {
    204: void;
};

export type ProcessEvidenceGroupsCallbackControllerRunResponse = ProcessEvidenceGroupsCallbackControllerRunResponses[keyof ProcessEvidenceGroupsCallbackControllerRunResponses];

export type ProcessEvidencesCallbackControllerRunData = {
    body: {
        operation: string;
        result: 'OK' | 'KO';
        data: {
            evidenceId: string;
            evidenceGroupId: string;
            caseFileId: string;
        };
    };
    path?: never;
    query?: never;
    url: '/evidences/callback';
};

export type ProcessEvidencesCallbackControllerRunResponses = {
    204: void;
};

export type ProcessEvidencesCallbackControllerRunResponse = ProcessEvidencesCallbackControllerRunResponses[keyof ProcessEvidencesCallbackControllerRunResponses];

export type ThumbnailEvidenceControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        evidenceGroupId: string;
        id: string;
        size: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/evidences/{id}/thumbnail/{size}';
};

export type ThumbnailEvidenceControllerRunResponses = {
    200: {
        url: string;
    };
};

export type ThumbnailEvidenceControllerRunResponse = ThumbnailEvidenceControllerRunResponses[keyof ThumbnailEvidenceControllerRunResponses];

export type UpdateFavoriteEvidenceControllerRunData = {
    body: {
        favorite: boolean;
    };
    path: {
        evidenceGroupId: string;
        caseFileId: string;
        id: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/evidences/{id}/favorite';
};

export type UpdateFavoriteEvidenceControllerRunResponses = {
    204: void;
};

export type UpdateFavoriteEvidenceControllerRunResponse = UpdateFavoriteEvidenceControllerRunResponses[keyof UpdateFavoriteEvidenceControllerRunResponses];

export type UploadUrlEvidenceControllerRunData = {
    body: {
        hash: string;
        fileName: string;
    };
    path: {
        caseFileId: string;
        evidenceGroupId: string;
        id: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/evidences/{id}/upload-url';
};

export type UploadUrlEvidenceControllerRunResponses = {
    201: {
        uploadFileUrl: string;
        expiration: string;
    };
};

export type UploadUrlEvidenceControllerRunResponse = UploadUrlEvidenceControllerRunResponses[keyof UploadUrlEvidenceControllerRunResponses];

export type CancelLargeEvidenceUploadControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        evidenceGroupId: string;
        id: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/large-evidence-uploads/{id}';
};

export type CancelLargeEvidenceUploadControllerRunResponses = {
    204: void;
};

export type CancelLargeEvidenceUploadControllerRunResponse = CancelLargeEvidenceUploadControllerRunResponses[keyof CancelLargeEvidenceUploadControllerRunResponses];

export type CreateEvidenceGroupCloseRequestControllerRunData = {
    body: {
        id: string;
        userAgent?: string;
    };
    path: {
        caseFileId: string;
        evidenceGroupId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/close-request';
};

export type CreateEvidenceGroupCloseRequestControllerRunResponses = {
    201: unknown;
};

export type ListLargeEvidenceUploadsControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        evidenceGroupId: string;
    };
    query?: {
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/large-evidence-uploads';
};

export type ListLargeEvidenceUploadsControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            fileName: string;
            chunkSizeMB: number;
            totalSizeMB: number;
            biggestUploadedOffset: number;
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListLargeEvidenceUploadsControllerRunResponse = ListLargeEvidenceUploadsControllerRunResponses[keyof ListLargeEvidenceUploadsControllerRunResponses];

export type CreateLargeEvidenceUploadControllerRunData = {
    body: {
        id: string;
        evidenceId: string;
        totalSizeMB: number;
        title: string;
        fileName: string;
        capturedAt: string;
    };
    path: {
        caseFileId: string;
        evidenceGroupId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/large-evidence-uploads';
};

export type CreateLargeEvidenceUploadControllerRunResponses = {
    201: unknown;
};

export type ListAndCreateEvidencePendingOffsetsControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        evidenceGroupId: string;
        id: string;
    };
    query: {
        count: number;
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/large-evidence-uploads/{id}/pending-offsets';
};

export type ListAndCreateEvidencePendingOffsetsControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            largeEvidenceUploadId: string;
            offset: number;
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListAndCreateEvidencePendingOffsetsControllerRunResponse = ListAndCreateEvidencePendingOffsetsControllerRunResponses[keyof ListAndCreateEvidencePendingOffsetsControllerRunResponses];

export type NotifyEvidenceUploadedOffsetControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        evidenceGroupId: string;
        largeEvidenceUploadId: string;
        id: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/large-evidence-uploads/{largeEvidenceUploadId}/pending-offsets/{id}/uploaded';
};

export type NotifyEvidenceUploadedOffsetControllerRunResponses = {
    204: void;
};

export type NotifyEvidenceUploadedOffsetControllerRunResponse = NotifyEvidenceUploadedOffsetControllerRunResponses[keyof NotifyEvidenceUploadedOffsetControllerRunResponses];

export type ShowEvidencePendingOffsetUploadUrlControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        evidenceGroupId: string;
        largeEvidenceUploadId: string;
        id: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/large-evidence-uploads/{largeEvidenceUploadId}/pending-offsets/{id}/upload-url';
};

export type ShowEvidencePendingOffsetUploadUrlControllerRunResponses = {
    200: {
        url: string;
    };
};

export type ShowEvidencePendingOffsetUploadUrlControllerRunResponse = ShowEvidencePendingOffsetUploadUrlControllerRunResponses[keyof ShowEvidencePendingOffsetUploadUrlControllerRunResponses];

export type ListNotificationCertificatesControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        notificationRequestId: string;
        receiverId: string;
    };
    query?: {
        filter?: {
            partial: boolean;
            language?: 'en_GB' | 'es_ES';
            id?: string;
        };
        order?: {
            createdAt?: 'ASC' | 'DESC';
        };
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/case-files/{caseFileId}/notification-requests/{notificationRequestId}/receivers/{receiverId}/certificates';
};

export type ListNotificationCertificatesControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            notificationRequestId: string;
            receiverId: string;
            partial: boolean;
            status: 'CERTIFYING' | 'DRAFT' | 'CERTIFIED';
            createdAt: string;
            certifiedAt?: string;
            language: 'en_GB' | 'es_ES';
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListNotificationCertificatesControllerRunResponse = ListNotificationCertificatesControllerRunResponses[keyof ListNotificationCertificatesControllerRunResponses];

export type CreateNotificationCertificateControllerRunData = {
    body: {
        id: string;
        language?: 'en_GB' | 'es_ES';
    };
    path: {
        caseFileId: string;
        notificationRequestId: string;
        receiverId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/notification-requests/{notificationRequestId}/receivers/{receiverId}/certificates';
};

export type CreateNotificationCertificateControllerRunResponses = {
    201: unknown;
};

export type ProcessNotificationCertificatesCallbackControllerRunData = {
    body: {
        eventType: string;
        data: {
            reportId: string;
        };
    };
    path?: never;
    query?: never;
    url: '/notification-certificates/callback';
};

export type ProcessNotificationCertificatesCallbackControllerRunResponses = {
    204: void;
};

export type ProcessNotificationCertificatesCallbackControllerRunResponse = ProcessNotificationCertificatesCallbackControllerRunResponses[keyof ProcessNotificationCertificatesCallbackControllerRunResponses];

export type ShowNotificationCertificateDocumentUrlControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        notificationRequestId: string;
        receiverId: string;
        certificateId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/notification-requests/{notificationRequestId}/receivers/{receiverId}/certificates/{certificateId}/document-url';
};

export type ShowNotificationCertificateDocumentUrlControllerRunResponses = {
    200: {
        documentUrl: string;
    };
};

export type ShowNotificationCertificateDocumentUrlControllerRunResponse = ShowNotificationCertificateDocumentUrlControllerRunResponses[keyof ShowNotificationCertificateDocumentUrlControllerRunResponses];

export type ShowNotificationCertificatePackageUrlControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        notificationRequestId: string;
        receiverId: string;
        certificateId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/notification-requests/{notificationRequestId}/receivers/{receiverId}/certificates/{certificateId}/package-url';
};

export type ShowNotificationCertificatePackageUrlControllerRunResponses = {
    200: {
        packageUrl: string;
    };
};

export type ShowNotificationCertificatePackageUrlControllerRunResponse = ShowNotificationCertificatePackageUrlControllerRunResponses[keyof ShowNotificationCertificatePackageUrlControllerRunResponses];

export type ActivateNotificationRequestControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        notificationRequestId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/notification-requests/{notificationRequestId}/activate';
};

export type ActivateNotificationRequestControllerRunResponses = {
    200: unknown;
};

export type CreateMassiveNotificationReceiversControllerRunData = {
    body: {
        receivers: Array<{
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            phoneNumber?: string;
            phonePrefix?: string;
        }>;
    };
    path: {
        caseFileId: string;
        notificationRequestId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/notification-requests/{notificationRequestId}/receivers/massive';
};

export type CreateMassiveNotificationReceiversControllerRunResponses = {
    201: unknown;
};

export type ListNotificationReceiversControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        notificationRequestId: string;
    };
    query?: {
        filter?: {
            id?: string;
        };
        order?: {
            createdAt?: 'ASC' | 'DESC';
            email?: 'ASC' | 'DESC';
        };
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/case-files/{caseFileId}/notification-requests/{notificationRequestId}/receivers';
};

export type ListNotificationReceiversControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            notificationRequestId: string;
            status: 'INVALID' | 'READY_TO_SEND' | 'SENT' | 'READ' | 'ANSWERED' | 'ERROR';
            validationError?: 'TAKEN' | 'IS_DEFINED' | 'IS_INVALID';
            answer?: string;
            firstName?: string;
            lastName?: string;
            email?: string;
            phonePrefix?: string;
            phoneNumber?: string;
            statusUpdatedAt: string;
            otpRequired: boolean;
            sendWaUrl: boolean;
            emailBounced: boolean;
            createdAt: string;
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListNotificationReceiversControllerRunResponse = ListNotificationReceiversControllerRunResponses[keyof ListNotificationReceiversControllerRunResponses];

export type CreateNotificationReceiverControllerRunData = {
    body: {
        id: string;
        firstName: string;
        lastName: string;
        email: string;
        phoneNumber?: string;
        phonePrefix?: string;
        otpRequired?: boolean;
        sendWaUrl?: boolean;
    };
    path: {
        caseFileId: string;
        notificationRequestId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/notification-requests/{notificationRequestId}/receivers';
};

export type CreateNotificationReceiverControllerRunResponses = {
    201: unknown;
};

export type CreateNotificationRequestControllerRunData = {
    body: {
        id: string;
        type?: 'NO_RESPONSE' | 'ACCEPTED_OR_NOT' | 'RECEIVED_AGREE';
        subject: string;
        content: string;
        language: 'en_GB' | 'es_ES';
        otpByDefault?: boolean;
        sendWaUrlByDefault?: boolean;
    };
    path: {
        caseFileId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/notification-requests';
};

export type CreateNotificationRequestControllerRunResponses = {
    201: unknown;
};

export type DeleteInvalidNotificationReceiversControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        notificationRequestId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/notification-requests/{notificationRequestId}/invalid-receivers';
};

export type DeleteInvalidNotificationReceiversControllerRunResponses = {
    200: unknown;
};

export type DeleteNotificationReceiverControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        notificationRequestId: string;
        receiverId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/notification-requests/{notificationRequestId}/receivers/{receiverId}';
};

export type DeleteNotificationReceiverControllerRunResponses = {
    200: unknown;
};

export type UpdateNotificationReceiverControllerRunData = {
    body: {
        firstName?: string;
        lastName?: string;
        email?: string;
        phonePrefix?: string;
        phoneNumber?: string;
    };
    path: {
        caseFileId: string;
        notificationRequestId: string;
        receiverId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/notification-requests/{notificationRequestId}/receivers/{receiverId}';
};

export type UpdateNotificationReceiverControllerRunResponses = {
    200: unknown;
};

export type DeleteNotificationRequestControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        notificationRequestId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/notification-requests/{notificationRequestId}';
};

export type DeleteNotificationRequestControllerRunResponses = {
    200: unknown;
};

export type ShowNotificationRequestControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        notificationRequestId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/notification-requests/{notificationRequestId}';
};

export type ShowNotificationRequestControllerRunResponses = {
    200: {
        id: string;
        code: string;
        subject: string;
        content: string;
        language: 'en_GB' | 'es_ES';
        status: 'CREATING' | 'DRAFT' | 'IN_PROCESS' | 'SENT' | 'PARTIALLY_READ' | 'FULLY_READ' | 'PARTIALLY_ANSWERED' | 'FULLY_ANSWERED';
        type: 'NO_RESPONSE' | 'ACCEPTED_OR_NOT' | 'RECEIVED_AGREE';
        statusUpdatedAt: string;
        sentAt?: string;
        createdAt: string;
        otpByDefault: boolean;
        sendWaUrlByDefault: boolean;
        caseFile: {
            id: string;
            useCaseId: string;
            name: string;
            code: string;
            ownerId: string;
        };
        owner: {
            id: string;
            firstName: string;
            lastName: string;
            role: string;
            email: string;
        };
        createdBy?: {
            id: string;
            firstName: string;
            lastName: string;
            role: string;
            email: string;
        };
        receiverStats: {
            total: number;
            bounced: number;
            valid: number;
        };
    };
};

export type ShowNotificationRequestControllerRunResponse = ShowNotificationRequestControllerRunResponses[keyof ShowNotificationRequestControllerRunResponses];

export type UpdateNotificationRequestControllerRunData = {
    body: {
        type?: 'NO_RESPONSE' | 'ACCEPTED_OR_NOT' | 'RECEIVED_AGREE';
        subject?: string;
        content?: string;
        language?: 'en_GB' | 'es_ES';
    };
    path: {
        caseFileId: string;
        notificationRequestId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/notification-requests/{notificationRequestId}';
};

export type UpdateNotificationRequestControllerRunResponses = {
    200: unknown;
};

export type DuplicateNotificationRequestControllerRunData = {
    body: {
        caseFileId?: string;
        id: string;
        subject: string;
    };
    path: {
        caseFileId: string;
        notificationRequestId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/notification-requests/{notificationRequestId}/duplicate';
};

export type DuplicateNotificationRequestControllerRunResponses = {
    201: unknown;
};

export type ListNotificationRequestsControllerRunData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: {
        filter?: {
            status?: 'CREATING' | 'DRAFT' | 'IN_PROCESS' | 'SENT' | 'PARTIALLY_READ' | 'FULLY_READ' | 'PARTIALLY_ANSWERED' | 'FULLY_ANSWERED';
            statuses?: Array<'CREATING' | 'DRAFT' | 'IN_PROCESS' | 'SENT' | 'PARTIALLY_READ' | 'FULLY_READ' | 'PARTIALLY_ANSWERED' | 'FULLY_ANSWERED'>;
            search?: string;
            caseFileIds?: Array<string>;
            receiversSearch?: string;
        };
        order?: {
            createdAt?: 'ASC' | 'DESC';
        };
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/users/{userId}/notification-requests';
};

export type ListNotificationRequestsControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            code: string;
            subject: string;
            status: 'CREATING' | 'DRAFT' | 'IN_PROCESS' | 'SENT' | 'PARTIALLY_READ' | 'FULLY_READ' | 'PARTIALLY_ANSWERED' | 'FULLY_ANSWERED';
            type: 'NO_RESPONSE' | 'ACCEPTED_OR_NOT' | 'RECEIVED_AGREE';
            statusUpdatedAt: string;
            createdAt: string;
            sentAt?: string;
            otpByDefault: boolean;
            receiverStats: {
                firstEmail: string;
                total: number;
            };
            sendWaUrlByDefault: boolean;
            caseFile: {
                id: string;
                useCaseId: string;
                name: string;
                code: string;
            };
            owner: {
                id: string;
                firstName: string;
                lastName: string;
            };
            createdBy?: {
                id: string;
                firstName: string;
                lastName: string;
            };
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListNotificationRequestsControllerRunResponse = ListNotificationRequestsControllerRunResponses[keyof ListNotificationRequestsControllerRunResponses];

export type ProcessNotificationsCallbackControllerRunData = {
    body: {
        eventType: string;
        data: {
            notificationId?: string;
            notificationAttachmentId?: string;
        };
    };
    path?: never;
    query?: never;
    url: '/notifications/callback';
};

export type ProcessNotificationsCallbackControllerRunResponses = {
    204: void;
};

export type ProcessNotificationsCallbackControllerRunResponse = ProcessNotificationsCallbackControllerRunResponses[keyof ProcessNotificationsCallbackControllerRunResponses];

export type SendNotificationRequestControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        notificationRequestId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/notification-requests/{notificationRequestId}/send';
};

export type SendNotificationRequestControllerRunResponses = {
    200: unknown;
};

export type UpdateNotificationRequestCaseFileIdControllerRunData = {
    body: {
        caseFileId: string;
    };
    path: {
        caseFileId: string;
        notificationRequestId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/notification-requests/{notificationRequestId}/case-file-id';
};

export type UpdateNotificationRequestCaseFileIdControllerRunResponses = {
    200: unknown;
};

export type ListSignaturePartialCertificatesControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        requestId: string;
        documentId: string;
    };
    query?: {
        filter?: {
            id?: string;
        };
        order?: {
            createdAt?: 'ASC' | 'DESC';
        };
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/case-files/{caseFileId}/signature-requests/{requestId}/documents/{documentId}/partial-certificates';
};

export type ListSignaturePartialCertificatesControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            requestId: string;
            documentId: string;
            status: 'CERTIFYING' | 'DRAFT' | 'CERTIFIED';
            createdAt: string;
            certifiedAt?: string;
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListSignaturePartialCertificatesControllerRunResponse = ListSignaturePartialCertificatesControllerRunResponses[keyof ListSignaturePartialCertificatesControllerRunResponses];

export type CreateSignaturePartialCertificateControllerRunData = {
    body: {
        id: string;
    };
    path: {
        caseFileId: string;
        requestId: string;
        documentId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/signature-requests/{requestId}/documents/{documentId}/partial-certificates';
};

export type CreateSignaturePartialCertificateControllerRunResponses = {
    201: unknown;
};

export type ProcessSignatureCertificatesCallbackControllerRunData = {
    body: {
        operationType: 'REPORTS';
        data: {
            processId: string;
        };
    };
    path?: never;
    query?: never;
    url: '/signature-certificates/callback';
};

export type ProcessSignatureCertificatesCallbackControllerRunResponses = {
    204: void;
};

export type ProcessSignatureCertificatesCallbackControllerRunResponse = ProcessSignatureCertificatesCallbackControllerRunResponses[keyof ProcessSignatureCertificatesCallbackControllerRunResponses];

export type ShowSignatureCertificateDocumentUrlControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        requestId: string;
        documentId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/signature-requests/{requestId}/documents/{documentId}/certificates/document-url';
};

export type ShowSignatureCertificateDocumentUrlControllerRunResponses = {
    200: {
        documentUrl: string;
    };
};

export type ShowSignatureCertificateDocumentUrlControllerRunResponse = ShowSignatureCertificateDocumentUrlControllerRunResponses[keyof ShowSignatureCertificateDocumentUrlControllerRunResponses];

export type ShowSignatureCertificatePackageUrlControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        requestId: string;
        documentId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/signature-requests/{requestId}/documents/{documentId}/certificates/package-url';
};

export type ShowSignatureCertificatePackageUrlControllerRunResponses = {
    200: {
        packageUrl: string;
    };
};

export type ShowSignatureCertificatePackageUrlControllerRunResponse = ShowSignatureCertificatePackageUrlControllerRunResponses[keyof ShowSignatureCertificatePackageUrlControllerRunResponses];

export type ShowSignatureCertificateSignaturesUrlControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        requestId: string;
        documentId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/signature-requests/{requestId}/documents/{documentId}/certificates/signatures-url';
};

export type ShowSignatureCertificateSignaturesUrlControllerRunResponses = {
    200: {
        signaturesUrl: string;
    };
};

export type ShowSignatureCertificateSignaturesUrlControllerRunResponse = ShowSignatureCertificateSignaturesUrlControllerRunResponses[keyof ShowSignatureCertificateSignaturesUrlControllerRunResponses];

export type ShowSignatureDocumentSignedDocumentUrlControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        requestId: string;
        documentId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/signature-requests/{requestId}/documents/{documentId}/signed-document-url';
};

export type ShowSignatureDocumentSignedDocumentUrlControllerRunResponses = {
    200: {
        signedDocumentUrl: string;
    };
};

export type ShowSignatureDocumentSignedDocumentUrlControllerRunResponse = ShowSignatureDocumentSignedDocumentUrlControllerRunResponses[keyof ShowSignatureDocumentSignedDocumentUrlControllerRunResponses];

export type ShowSignaturePartialCertificateDocumentUrlControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        requestId: string;
        documentId: string;
        certificateId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/signature-requests/{requestId}/documents/{documentId}/partial-certificates/{certificateId}/document-url';
};

export type ShowSignaturePartialCertificateDocumentUrlControllerRunResponses = {
    200: {
        documentUrl: string;
    };
};

export type ShowSignaturePartialCertificateDocumentUrlControllerRunResponse = ShowSignaturePartialCertificateDocumentUrlControllerRunResponses[keyof ShowSignaturePartialCertificateDocumentUrlControllerRunResponses];

export type ShowSignaturePartialCertificatePackageUrlControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        requestId: string;
        documentId: string;
        certificateId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/signature-requests/{requestId}/documents/{documentId}/partial-certificates/{certificateId}/package-url';
};

export type ShowSignaturePartialCertificatePackageUrlControllerRunResponses = {
    200: {
        packageUrl: string;
    };
};

export type ShowSignaturePartialCertificatePackageUrlControllerRunResponse = ShowSignaturePartialCertificatePackageUrlControllerRunResponses[keyof ShowSignaturePartialCertificatePackageUrlControllerRunResponses];

export type ShowSignaturePartialCertificateSignaturesUrlControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        requestId: string;
        documentId: string;
        certificateId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/signature-requests/{requestId}/documents/{documentId}/partial-certificates/{certificateId}/signatures-url';
};

export type ShowSignaturePartialCertificateSignaturesUrlControllerRunResponses = {
    200: {
        signaturesUrl: string;
    };
};

export type ShowSignaturePartialCertificateSignaturesUrlControllerRunResponse = ShowSignaturePartialCertificateSignaturesUrlControllerRunResponses[keyof ShowSignaturePartialCertificateSignaturesUrlControllerRunResponses];

export type ActivateSignatureRequestControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        requestId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/signature-requests/{requestId}/activate';
};

export type ActivateSignatureRequestControllerRunResponses = {
    200: unknown;
};

export type CancelSignatureRequestControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        requestId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/signature-requests/{requestId}/cancel';
};

export type CancelSignatureRequestControllerRunResponses = {
    200: unknown;
};

export type CloseSignatureRequestControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        requestId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/signature-requests/{requestId}/close';
};

export type CloseSignatureRequestControllerRunResponses = {
    200: unknown;
};

export type CreateDocumentParticipantsControllerRunData = {
    body: {
        participantIds: Array<string>;
    };
    path: {
        caseFileId: string;
        requestId: string;
        documentId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/signature-requests/{requestId}/documents/{documentId}/participants';
};

export type CreateDocumentParticipantsControllerRunResponses = {
    201: unknown;
};

export type CreateMassiveSignatureParticipantsControllerRunData = {
    body: {
        participants: Array<{
            id: string;
            role: 'SIGNATORY' | 'OBSERVER' | 'VALIDATOR';
            firstName: string;
            lastName: string;
            email: string;
            phoneNumber?: string;
            phonePrefix?: string;
        }>;
    };
    path: {
        caseFileId: string;
        requestId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/signature-requests/{requestId}/participants/massive';
};

export type CreateMassiveSignatureParticipantsControllerRunResponses = {
    201: unknown;
};

export type ListSignatureDocumentsControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        requestId: string;
    };
    query?: {
        filter?: {
            status?: 'PENDING' | 'READY_TO_SIGN' | 'PARTIALLY_SIGNED' | 'SIGNED' | 'REJECTED' | 'ERROR';
            fileName?: string;
            groupIds?: Array<string>;
        };
        order?: {
            createdAt?: 'ASC' | 'DESC';
            groupIndex?: 'ASC' | 'DESC';
        };
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/case-files/{caseFileId}/signature-requests/{requestId}/documents';
};

export type ListSignatureDocumentsControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            requestId: string;
            groupId?: string;
            status: 'PENDING' | 'READY_TO_SIGN' | 'PARTIALLY_SIGNED' | 'SIGNED' | 'REJECTED' | 'ERROR';
            title: string;
            fileName: string;
            fileSize?: number;
            convertToPdf: boolean;
            participantStats: {
                signatories: number;
                observers: number;
            };
            signatoryStatusStats: {
                pending: number;
                readyToSign: number;
                signed: number;
                rejected: number;
            };
            signatoryCoordinatesStats: {
                defined: number;
                missing: number;
            };
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListSignatureDocumentsControllerRunResponse = ListSignatureDocumentsControllerRunResponses[keyof ListSignatureDocumentsControllerRunResponses];

export type CreateSignatureDocumentControllerRunData = {
    body: {
        id: string;
        groupId?: string;
        hash: string;
        title: string;
        fileName: string;
        fileSize?: number;
        convertToPdf?: boolean;
    };
    path: {
        caseFileId: string;
        requestId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/signature-requests/{requestId}/documents';
};

export type CreateSignatureDocumentControllerRunResponses = {
    201: {
        url?: string;
    };
};

export type CreateSignatureDocumentControllerRunResponse = CreateSignatureDocumentControllerRunResponses[keyof CreateSignatureDocumentControllerRunResponses];

export type ListSignatureParticipantsControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        requestId: string;
    };
    query?: {
        filter?: {
            role?: 'SIGNATORY' | 'OBSERVER' | 'VALIDATOR';
            groupIds?: Array<string>;
            id?: string;
        };
        order?: {
            createdAt?: 'ASC' | 'DESC';
            groupIndex?: 'ASC' | 'DESC';
            email?: 'ASC' | 'DESC';
        };
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/case-files/{caseFileId}/signature-requests/{requestId}/participants';
};

export type ListSignatureParticipantsControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            requestId: string;
            groupId?: string;
            role: string;
            firstName?: string;
            lastName?: string;
            email?: string;
            createdAt: string;
            phoneNumber?: string;
            phonePrefix?: string;
            participantStats?: {
                validators: number;
            };
            editable: boolean;
            emailBounced: boolean;
            valid: boolean;
            validationError?: 'TAKEN' | 'IS_DEFINED' | 'IS_INVALID';
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListSignatureParticipantsControllerRunResponse = ListSignatureParticipantsControllerRunResponses[keyof ListSignatureParticipantsControllerRunResponses];

export type CreateSignatureParticipantControllerRunData = {
    body: {
        id: string;
        groupId?: string;
        role: 'SIGNATORY' | 'OBSERVER' | 'VALIDATOR';
        firstName: string;
        lastName: string;
        email: string;
        linkToAllDocuments?: boolean;
        phoneNumber?: string;
        phonePrefix?: string;
    };
    path: {
        caseFileId: string;
        requestId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/signature-requests/{requestId}/participants';
};

export type CreateSignatureParticipantControllerRunResponses = {
    201: unknown;
};

export type ListSignatureRequestsByCaseFileControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
    };
    query?: {
        filter?: {
            search?: string;
            status?: 'CREATING' | 'DRAFT' | 'ACTIVE' | 'PARTIALLY_SIGNED' | 'FULLY_SIGNED' | 'CANCELLED' | 'COMPLETED' | 'REJECTED' | 'CLOSING' | 'COMPLETED_MANUAL';
            statuses?: Array<'CREATING' | 'DRAFT' | 'ACTIVE' | 'PARTIALLY_SIGNED' | 'FULLY_SIGNED' | 'CANCELLED' | 'COMPLETED' | 'REJECTED' | 'CLOSING' | 'COMPLETED_MANUAL'>;
            createdFrom?: string;
            createdUntil?: string;
            id?: string;
        };
        order?: {
            createdAt?: 'ASC' | 'DESC';
        };
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/case-files/{caseFileId}/signature-requests';
};

export type ListSignatureRequestsByCaseFileControllerRunResponses = {
    200: {
        data?: Array<{
            /**
             * @deprecated
             */
            caseFileId: string;
            id: string;
            code: string;
            name: string;
            language: string;
            status: 'CREATING' | 'DRAFT' | 'ACTIVE' | 'PARTIALLY_SIGNED' | 'FULLY_SIGNED' | 'CANCELLED' | 'COMPLETED' | 'REJECTED' | 'CLOSING' | 'COMPLETED_MANUAL';
            createdAt: string;
            activatedAt?: string;
            completedAt?: string;
            closeCondition: 'ALL_REQUIRED' | 'PARTIAL_ALLOWED';
            caseFile: {
                id: string;
                useCaseId: string;
                name: string;
                code: string;
            };
            owner: {
                id: string;
                firstName: string;
                lastName: string;
                role: string;
            };
            createdBy?: {
                id: string;
                firstName: string;
                lastName: string;
                role: string;
            };
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListSignatureRequestsByCaseFileControllerRunResponse = ListSignatureRequestsByCaseFileControllerRunResponses[keyof ListSignatureRequestsByCaseFileControllerRunResponses];

export type CreateSignatureRequestControllerRunData = {
    body: {
        id: string;
        name: string;
        language: 'en_GB' | 'es_ES';
        signatureType?: 'INTERPOSITION' | 'ADVANCED';
        dashboardUrl?: 'NONE' | 'ANONYMIZED';
        sequence?: 'PARALLEL' | 'CONFIGURABLE';
        deadline: string;
        objectiveId?: string;
        closeCondition?: 'ALL_REQUIRED' | 'PARTIAL_ALLOWED';
    };
    path: {
        caseFileId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/signature-requests';
};

export type CreateSignatureRequestControllerRunResponses = {
    201: unknown;
};

export type DeleteDocumentParticipantControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        requestId: string;
        documentId: string;
        id: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/signature-requests/{requestId}/documents/{documentId}/participants/{id}';
};

export type DeleteDocumentParticipantControllerRunResponses = {
    200: unknown;
};

export type DeleteInvalidSignatureParticipantsControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        requestId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/signature-requests/{requestId}/invalid-participants';
};

export type DeleteInvalidSignatureParticipantsControllerRunResponses = {
    200: unknown;
};

export type DeleteSignatureDocumentControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        requestId: string;
        documentId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/signature-requests/{requestId}/documents/{documentId}';
};

export type DeleteSignatureDocumentControllerRunResponses = {
    200: unknown;
};

export type UpdateSignatureDocumentControllerRunData = {
    body: {
        groupId?: string;
    };
    path: {
        caseFileId: string;
        requestId: string;
        documentId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/signature-requests/{requestId}/documents/{documentId}';
};

export type UpdateSignatureDocumentControllerRunResponses = {
    200: unknown;
};

export type DeleteSignatureParticipantControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        requestId: string;
        participantId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/signature-requests/{requestId}/participants/{participantId}';
};

export type DeleteSignatureParticipantControllerRunResponses = {
    200: unknown;
};

export type UpdateSignatureParticipantControllerRunData = {
    body: {
        groupId?: string;
        firstName?: string;
        lastName?: string;
        email?: string;
        phonePrefix?: string;
        phoneNumber?: string;
    };
    path: {
        caseFileId: string;
        requestId: string;
        participantId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/signature-requests/{requestId}/participants/{participantId}';
};

export type UpdateSignatureParticipantControllerRunResponses = {
    200: unknown;
};

export type DeleteSignatureRequestControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        requestId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/signature-requests/{requestId}';
};

export type DeleteSignatureRequestControllerRunResponses = {
    200: unknown;
};

export type ShowSignatureRequestControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        requestId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/signature-requests/{requestId}';
};

export type ShowSignatureRequestControllerRunResponses = {
    200: {
        /**
         * @deprecated
         */
        caseFileId: string;
        id: string;
        code: string;
        name: string;
        language: string;
        status: 'CREATING' | 'DRAFT' | 'ACTIVE' | 'PARTIALLY_SIGNED' | 'FULLY_SIGNED' | 'CANCELLED' | 'COMPLETED' | 'REJECTED' | 'CLOSING' | 'COMPLETED_MANUAL';
        createdAt: string;
        signatureType: 'INTERPOSITION' | 'ADVANCED';
        dashboardUrl: 'NONE' | 'ANONYMIZED';
        sequence: 'PARALLEL' | 'CONFIGURABLE';
        activatedAt?: string;
        completedAt?: string;
        objectiveId?: string;
        deadline: string;
        closeCondition: 'ALL_REQUIRED' | 'PARTIAL_ALLOWED';
        signatoryStats: {
            total: number;
            bounced: number;
            valid: number;
        };
        observerStats: {
            total: number;
            bounced: number;
            valid: number;
        };
        validatorStats: {
            total: number;
            bounced: number;
            assignedToSignatories: number;
            assignedToDocuments: number;
            valid: number;
        };
        caseFile: {
            id: string;
            useCaseId: string;
            name: string;
            code: string;
            ownerId: string;
        };
        owner: {
            id: string;
            firstName: string;
            lastName: string;
            role: string;
        };
        createdBy?: {
            id: string;
            firstName: string;
            lastName: string;
            role: string;
        };
    };
};

export type ShowSignatureRequestControllerRunResponse = ShowSignatureRequestControllerRunResponses[keyof ShowSignatureRequestControllerRunResponses];

export type UpdateSignatureRequestControllerRunData = {
    body: {
        name?: string;
        language?: 'en_GB' | 'es_ES';
        deadline?: string;
        dashboardUrl?: 'NONE' | 'ANONYMIZED';
        objectiveId?: string;
    };
    path: {
        caseFileId: string;
        requestId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/signature-requests/{requestId}';
};

export type UpdateSignatureRequestControllerRunResponses = {
    200: unknown;
};

export type DraftSignatureRequestControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        requestId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/signature-requests/{requestId}/draft';
};

export type DraftSignatureRequestControllerRunResponses = {
    200: unknown;
};

export type DuplicateSignatureRequestControllerRunData = {
    body: {
        caseFileId?: string;
        id: string;
        name: string;
        deadline: string;
    };
    path: {
        caseFileId: string;
        requestId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/signature-requests/{requestId}/duplicate';
};

export type DuplicateSignatureRequestControllerRunResponses = {
    201: unknown;
};

export type ListDocumentObserversControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        requestId: string;
        documentId: string;
    };
    query?: {
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/case-files/{caseFileId}/signature-requests/{requestId}/documents/{documentId}/observers';
};

export type ListDocumentObserversControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            email: string;
            firstName: string;
            lastName: string;
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListDocumentObserversControllerRunResponse = ListDocumentObserversControllerRunResponses[keyof ListDocumentObserversControllerRunResponses];

export type ListDocumentSignatoriesControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        requestId: string;
        documentId: string;
    };
    query?: {
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/case-files/{caseFileId}/signature-requests/{requestId}/documents/{documentId}/signatories';
};

export type ListDocumentSignatoriesControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            groupId?: string;
            email: string;
            firstName: string;
            lastName: string;
            status: 'PENDING' | 'READY_TO_SIGN' | 'VALIDATING' | 'SIGNED' | 'REJECTED';
            coordinates: Array<{
                page: number;
                x: number;
                y: number;
            }>;
            uniqueValidator: boolean;
            phoneNumber?: string;
            phonePrefix?: string;
            participantStats: {
                validators: number;
            };
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListDocumentSignatoriesControllerRunResponse = ListDocumentSignatoriesControllerRunResponses[keyof ListDocumentSignatoriesControllerRunResponses];

export type ListSignatureParticipantsWithLinkedFlagControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        requestId: string;
        documentId: string;
    };
    query?: {
        filter?: {
            role?: 'SIGNATORY' | 'OBSERVER' | 'VALIDATOR';
            search?: string;
        };
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/case-files/{caseFileId}/signature-requests/{requestId}/documents/{documentId}/participants-with-linked-flag';
};

export type ListSignatureParticipantsWithLinkedFlagControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            requestId: string;
            role: 'SIGNATORY' | 'OBSERVER' | 'VALIDATOR';
            firstName: string;
            lastName: string;
            email: string;
            createdAt: string;
            isLinked: boolean;
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListSignatureParticipantsWithLinkedFlagControllerRunResponse = ListSignatureParticipantsWithLinkedFlagControllerRunResponses[keyof ListSignatureParticipantsWithLinkedFlagControllerRunResponses];

export type ListSignatureRequestsByUserControllerRunData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: {
        filter?: {
            search?: string;
            status?: 'CREATING' | 'DRAFT' | 'ACTIVE' | 'PARTIALLY_SIGNED' | 'FULLY_SIGNED' | 'CANCELLED' | 'COMPLETED' | 'REJECTED' | 'CLOSING' | 'COMPLETED_MANUAL';
            statuses?: Array<'CREATING' | 'DRAFT' | 'ACTIVE' | 'PARTIALLY_SIGNED' | 'FULLY_SIGNED' | 'CANCELLED' | 'COMPLETED' | 'REJECTED' | 'CLOSING' | 'COMPLETED_MANUAL'>;
            createdFrom?: string;
            createdUntil?: string;
            id?: string;
            caseFileIds?: Array<string>;
        };
        order?: {
            createdAt?: 'ASC' | 'DESC';
        };
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/users/{userId}/signature-requests';
};

export type ListSignatureRequestsByUserControllerRunResponses = {
    200: {
        data?: Array<{
            /**
             * @deprecated
             */
            caseFileId: string;
            id: string;
            code: string;
            name: string;
            language: string;
            status: 'CREATING' | 'DRAFT' | 'ACTIVE' | 'PARTIALLY_SIGNED' | 'FULLY_SIGNED' | 'CANCELLED' | 'COMPLETED' | 'REJECTED' | 'CLOSING' | 'COMPLETED_MANUAL';
            createdAt: string;
            activatedAt?: string;
            completedAt?: string;
            closeCondition: 'ALL_REQUIRED' | 'PARTIAL_ALLOWED';
            caseFile: {
                id: string;
                useCaseId: string;
                name: string;
                code: string;
            };
            owner: {
                id: string;
                firstName: string;
                lastName: string;
                role: string;
            };
            createdBy?: {
                id: string;
                firstName: string;
                lastName: string;
                role: string;
            };
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListSignatureRequestsByUserControllerRunResponse = ListSignatureRequestsByUserControllerRunResponses[keyof ListSignatureRequestsByUserControllerRunResponses];

export type ProcessSignatureDocumentObserversCallbackControllerRunData = {
    body: {
        operationType: string;
        data: {
            signatureRequestId: string;
            email: string;
            notification: {
                status: 'BOUNCED';
            };
        };
    };
    path?: never;
    query?: never;
    url: '/signature-document-observers/callback';
};

export type ProcessSignatureDocumentObserversCallbackControllerRunResponses = {
    204: void;
};

export type ProcessSignatureDocumentObserversCallbackControllerRunResponse = ProcessSignatureDocumentObserversCallbackControllerRunResponses[keyof ProcessSignatureDocumentObserversCallbackControllerRunResponses];

export type ProcessSignatureDocumentSignatoriesCallbackControllerRunData = {
    body: {
        operationType: string;
        data: {
            signatureRequestId: string;
            email: string;
            notification: {
                status: 'BOUNCED';
            };
        };
    };
    path?: never;
    query?: never;
    url: '/signature-document-signatories/callback';
};

export type ProcessSignatureDocumentSignatoriesCallbackControllerRunResponses = {
    204: void;
};

export type ProcessSignatureDocumentSignatoriesCallbackControllerRunResponse = ProcessSignatureDocumentSignatoriesCallbackControllerRunResponses[keyof ProcessSignatureDocumentSignatoriesCallbackControllerRunResponses];

export type ProcessSignatureDocumentValidatorsCallbackControllerRunData = {
    body: {
        operationType: string;
        data: {
            signatureRequestId: string;
            email: string;
            notification: {
                status: 'BOUNCED';
            };
        };
    };
    path?: never;
    query?: never;
    url: '/signature-document-validators/callback';
};

export type ProcessSignatureDocumentValidatorsCallbackControllerRunResponses = {
    204: void;
};

export type ProcessSignatureDocumentValidatorsCallbackControllerRunResponse = ProcessSignatureDocumentValidatorsCallbackControllerRunResponses[keyof ProcessSignatureDocumentValidatorsCallbackControllerRunResponses];

export type ProcessSignatureDocumentsCallbackControllerRunData = {
    body: {
        operationType: string;
        data: {
            signatureRequestId: string;
            documentId: string;
            status: string;
        };
    };
    path?: never;
    query?: never;
    url: '/signature-documents/callback';
};

export type ProcessSignatureDocumentsCallbackControllerRunResponses = {
    204: void;
};

export type ProcessSignatureDocumentsCallbackControllerRunResponse = ProcessSignatureDocumentsCallbackControllerRunResponses[keyof ProcessSignatureDocumentsCallbackControllerRunResponses];

export type ProcessSignatureRequestsCallbackControllerRunData = {
    body: {
        operationType: string;
        data: {
            signatureRequestId: string;
            status: string;
        };
    };
    path?: never;
    query?: never;
    url: '/signature-requests/callback';
};

export type ProcessSignatureRequestsCallbackControllerRunResponses = {
    204: void;
};

export type ProcessSignatureRequestsCallbackControllerRunResponse = ProcessSignatureRequestsCallbackControllerRunResponses[keyof ProcessSignatureRequestsCallbackControllerRunResponses];

export type ResendSignatureRequestControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        requestId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/signature-requests/{requestId}/resend';
};

export type ResendSignatureRequestControllerRunResponses = {
    200: unknown;
};

export type ShowSignatureDocumentConvertedDownloadUrlControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        requestId: string;
        documentId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/signature-requests/{requestId}/documents/{documentId}/converted-download-url';
};

export type ShowSignatureDocumentConvertedDownloadUrlControllerRunResponses = {
    200: {
        convertedDownloadUrl: string;
    };
};

export type ShowSignatureDocumentConvertedDownloadUrlControllerRunResponse = ShowSignatureDocumentConvertedDownloadUrlControllerRunResponses[keyof ShowSignatureDocumentConvertedDownloadUrlControllerRunResponses];

export type ShowSignatureDocumentDownloadUrlControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        requestId: string;
        documentId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/signature-requests/{requestId}/documents/{documentId}/download-url';
};

export type ShowSignatureDocumentDownloadUrlControllerRunResponses = {
    200: {
        downloadUrl: string;
    };
};

export type ShowSignatureDocumentDownloadUrlControllerRunResponse = ShowSignatureDocumentDownloadUrlControllerRunResponses[keyof ShowSignatureDocumentDownloadUrlControllerRunResponses];

export type UpdateDocumentSignatoryControllerRunData = {
    body: {
        groupId?: string;
        uniqueValidator?: boolean;
    };
    path: {
        caseFileId: string;
        requestId: string;
        documentId: string;
        signatoryId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/signature-requests/{requestId}/documents/{documentId}/signatories/{signatoryId}';
};

export type UpdateDocumentSignatoryControllerRunResponses = {
    200: unknown;
};

export type UpdateSignatureCoordinatesControllerRunData = {
    body: {
        coordinates: Array<{
            page: number;
            x: number;
            y: number;
        }>;
    };
    path: {
        caseFileId: string;
        requestId: string;
        documentId: string;
        signatoryId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/signature-requests/{requestId}/documents/{documentId}/signatories/{signatoryId}/coordinates';
};

export type UpdateSignatureCoordinatesControllerRunResponses = {
    200: unknown;
};

export type UpdateSignatureRequestCaseFileIdControllerRunData = {
    body: {
        caseFileId: string;
    };
    path: {
        caseFileId: string;
        requestId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/signature-requests/{requestId}/case-file-id';
};

export type UpdateSignatureRequestCaseFileIdControllerRunResponses = {
    200: unknown;
};

export type ListUseCasesControllerRunData = {
    body?: never;
    path: {
        companyId: string;
    };
    query?: {
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/companies/{companyId}/use-cases';
};

export type ListUseCasesControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            code: string;
            index: number;
            translations: Array<{
                id: string;
                name: string;
                language: string;
                tipsDescription: string;
                tipsList: Array<string>;
                purposeDossier: string;
            }>;
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListUseCasesControllerRunResponse = ListUseCasesControllerRunResponses[keyof ListUseCasesControllerRunResponses];

export type ListUseCasesControllerDeprecatedRunData = {
    body?: never;
    path?: never;
    query?: {
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/use-cases';
};

export type ListUseCasesControllerDeprecatedRunResponses = {
    200: {
        data?: Array<{
            id: string;
            code: string;
            index: number;
            translations: Array<{
                id: string;
                name: string;
                language: string;
                tipsDescription: string;
                tipsList: Array<string>;
                purposeDossier: string;
            }>;
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListUseCasesControllerDeprecatedRunResponse = ListUseCasesControllerDeprecatedRunResponses[keyof ListUseCasesControllerDeprecatedRunResponses];
