// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zCreateOpenIdSessionControllerRunResponse = z.object({
    jwt: z.string()
});

export const zCreateOpenIdSessionWithLegalTextsControllerRunBody = z.object({
    legalTextLanguage: z.enum(['en_GB', 'es_ES']),
    acceptServiceTermId: z.string().optional(),
    acceptPrivacyPolicyId: z.string().optional()
});

export const zCreateOpenIdSessionWithLegalTextsControllerRunResponse = z.object({
    jwt: z.string()
});

export const zCreatePasswordTokenControllerRunBody = z.object({
    email: z.string(),
    recoveredFrom: z.enum([
        'Web',
        'AppPro',
        'AppLite'
    ]).default('Web')
});

export const zDeleteSessionControllerRunResponse = z.void();

export const zCreateSessionControllerRunBody = z.unknown();

export const zCreateSessionControllerRunResponse = z.object({
    jwt: z.string()
});

export const zCreateSessionWithLegalTextsControllerRunBody = z.object({
    email: z.string(),
    password: z.string(),
    legalTextLanguage: z.enum(['en_GB', 'es_ES']),
    acceptServiceTermId: z.string().optional(),
    acceptPrivacyPolicyId: z.string().optional()
});

export const zCreateSessionWithLegalTextsControllerRunResponse = z.object({
    jwt: z.string()
});

export const zShowOpenIdUserInfoControllerRunResponse = z.object({
    firstName: z.string(),
    lastName: z.string(),
    companyId: z.string(),
    email: z.string()
});

export const zShowSessionInfoControllerRunPath = z.object({
    email: z.string()
});

export const zShowSessionInfoControllerRunResponse = z.object({
    type: z.enum(['Password', 'OpenId']),
    issuer: z.string().optional(),
    clientId: z.string().optional(),
    scope: z.array(z.string()).optional()
});

export const zUpdatePasswordWithPasswordTokenControllerRunBody = z.object({
    password: z.string(),
    passwordConfirmation: z.string()
});

export const zUpdatePasswordWithPasswordTokenControllerRunPath = z.object({
    id: z.string()
});

export const zUpdatePasswordWithPasswordTokenControllerRunResponse = z.void();

export const zCreateCaseFileControllerRunBody = z.object({
    id: z.uuid(),
    name: z.string().max(100),
    reference: z.string().max(32).optional(),
    description: z.string().optional(),
    useCaseId: z.uuid()
});

export const zCreateCaseFilesSharingControllerRunBody = z.object({
    userIds: z.array(z.string()),
    role: z.enum([
        'COLLABORATOR',
        'EDITOR',
        'MANAGER'
    ])
});

export const zCreateCaseFilesSharingControllerRunPath = z.object({
    caseFileId: z.string()
});

export const zDeleteCaseFilesSharingControllerRunPath = z.object({
    caseFileId: z.string(),
    id: z.string()
});

export const zDeleteCaseFilesSharingControllerRunResponse = z.void();

export const zUpdateCaseFilesSharingControllerRunBody = z.object({
    role: z.enum([
        'COLLABORATOR',
        'EDITOR',
        'MANAGER'
    ]).optional()
});

export const zUpdateCaseFilesSharingControllerRunPath = z.object({
    caseFileId: z.string(),
    id: z.string()
});

export const zUpdateCaseFilesSharingControllerRunResponse = z.void();

export const zListCaseFilesControllerRunPath = z.object({
    userId: z.string()
});

export const zListCaseFilesControllerRunQuery = z.object({
    filter: z.object({
        search: z.string().optional(),
        status: z.enum(['OPEN', 'CLOSED']).optional(),
        statuses: z.array(z.enum(['OPEN', 'CLOSED'])).optional(),
        createdById: z.uuid().optional(),
        ownerId: z.uuid().optional(),
        ownerOrSharedWithId: z.uuid().optional(),
        useCaseId: z.uuid().optional(),
        id: z.string().optional()
    }).optional(),
    order: z.object({
        createdAt: z.enum(['ASC', 'DESC']).optional()
    }).optional(),
    page: z.object({
        number: z.number().gte(1).default(1),
        size: z.number().gte(0).lte(100).default(20)
    }).optional()
});

export const zListCaseFilesControllerRunResponse = z.object({
    data: z.array(z.object({
        id: z.string(),
        code: z.string(),
        name: z.string(),
        useCaseId: z.string(),
        createdAt: z.string(),
        status: z.string(),
        owner: z.object({
            id: z.string(),
            firstName: z.string(),
            lastName: z.string()
        }),
        createdBy: z.object({
            id: z.string(),
            firstName: z.string(),
            lastName: z.string()
        }).optional()
    })).optional(),
    meta: z.object({
        totalElements: z.number().optional()
    }).optional()
});

export const zListCaseFilesSharingControllerRunPath = z.object({
    caseFileId: z.string()
});

export const zListCaseFilesSharingControllerRunQuery = z.object({
    page: z.object({
        number: z.number().gte(1).default(1),
        size: z.number().gte(0).lte(100).default(20)
    }).optional()
});

export const zListCaseFilesSharingControllerRunResponse = z.object({
    data: z.array(z.object({
        id: z.string(),
        caseFileId: z.string(),
        userId: z.string(),
        role: z.string(),
        user: z.object({
            role: z.string(),
            firstName: z.string(),
            lastName: z.string(),
            email: z.string()
        })
    })).optional(),
    meta: z.object({
        totalElements: z.number().optional()
    }).optional()
});

export const zShowCaseFileControllerRunPath = z.object({
    caseFileId: z.string()
});

export const zShowCaseFileControllerRunResponse = z.object({
    id: z.string(),
    code: z.string(),
    name: z.string(),
    useCaseId: z.string(),
    createdAt: z.string(),
    status: z.string(),
    owner: z.object({
        id: z.string(),
        firstName: z.string(),
        lastName: z.string()
    }),
    createdBy: z.object({
        id: z.string(),
        firstName: z.string(),
        lastName: z.string()
    }).optional()
});

export const zUpdateCaseFileControllerRunBody = z.object({
    status: z.enum(['OPEN', 'CLOSED']).optional(),
    name: z.string().optional(),
    reference: z.string().max(32).optional(),
    description: z.string().optional()
});

export const zUpdateCaseFileControllerRunPath = z.object({
    caseFileId: z.string()
});

export const zUpdateCaseFileControllerRunResponse = z.void();

export const zShowCaseFilesSharingControllerRunPath = z.object({
    caseFileId: z.string()
});

export const zShowCaseFilesSharingControllerRunResponse = z.object({
    id: z.string(),
    caseFileId: z.string(),
    userId: z.string(),
    role: z.string()
});

export const zCertifyDossierControllerRunPath = z.object({
    caseFileId: z.string(),
    dossierId: z.string()
});

export const zListDossiersControllerRunPath = z.object({
    caseFileId: z.string()
});

export const zListDossiersControllerRunQuery = z.object({
    filter: z.object({
        caseFileId: z.uuid().optional(),
        search: z.string().optional(),
        createdFrom: z.string().optional(),
        createdUntil: z.string().optional(),
        status: z.enum([
            'CERTIFYING',
            'DRAFT',
            'CERTIFIED'
        ]).optional(),
        statuses: z.array(z.enum([
            'CERTIFYING',
            'DRAFT',
            'CERTIFIED'
        ])).optional(),
        createdById: z.uuid().optional(),
        ownerIds: z.array(z.uuid()).optional(),
        id: z.string().optional()
    }).optional(),
    order: z.object({
        createdAt: z.enum(['ASC', 'DESC']).optional()
    }).optional(),
    page: z.object({
        number: z.number().gte(1).default(1),
        size: z.number().gte(0).lte(100).default(20)
    }).optional()
});

export const zListDossiersControllerRunResponse = z.object({
    data: z.array(z.object({
        id: z.string(),
        caseFileId: z.string(),
        code: z.string(),
        name: z.string(),
        status: z.string(),
        createdAt: z.string(),
        certifiedAt: z.string().optional(),
        evidencesCount: z.number(),
        evidenceGroupsCount: z.number(),
        visibility: z.string(),
        owner: z.object({
            id: z.string(),
            firstName: z.string(),
            lastName: z.string()
        }),
        createdBy: z.object({
            id: z.string(),
            firstName: z.string(),
            lastName: z.string()
        }).optional()
    })).optional(),
    meta: z.object({
        totalElements: z.number().optional()
    }).optional()
});

export const zCreateDossierControllerRunBody = z.object({
    dossierTemplateId: z.string().optional(),
    purpose: z.string().optional(),
    id: z.string(),
    modelId: z.string().optional(),
    name: z.string(),
    language: z.enum([
        'en_GB',
        'es_ES',
        'pt_PT'
    ]),
    filledFields: z.record(z.string(), z.unknown()).optional(),
    validityFrom: z.string(),
    validityTo: z.string(),
    accessToken: z.string().optional()
});

export const zCreateDossierControllerRunPath = z.object({
    caseFileId: z.string()
});

export const zCreateDossierExpressControllerRunBody = z.object({
    id: z.string(),
    modelId: z.string().optional(),
    evidenceIds: z.array(z.string()).optional(),
    name: z.string(),
    language: z.enum([
        'en_GB',
        'es_ES',
        'pt_PT'
    ])
});

export const zCreateDossierExpressControllerRunPath = z.object({
    caseFileId: z.string(),
    evidenceGroupId: z.string()
});

export const zDeleteDossierControllerRunPath = z.object({
    caseFileId: z.string(),
    dossierId: z.string()
});

export const zDeleteDossierControllerRunResponse = z.void();

export const zShowDossierControllerRunPath = z.object({
    caseFileId: z.string(),
    dossierId: z.string()
});

export const zShowDossierControllerRunResponse = z.object({
    dossierTemplateId: z.string(),
    purpose: z.string().optional(),
    dossierTemplateFilename: z.string().optional(),
    id: z.string(),
    modelId: z.string(),
    code: z.string(),
    name: z.string(),
    language: z.string(),
    filledFields: z.record(z.string(), z.unknown()),
    status: z.string(),
    visibility: z.string(),
    caseFileId: z.string(),
    createdAt: z.string(),
    evidencesCount: z.number(),
    evidenceGroupsCount: z.number(),
    certifiedAt: z.string().optional(),
    owner: z.object({
        id: z.string(),
        firstName: z.string(),
        lastName: z.string()
    }),
    createdBy: z.object({
        id: z.string(),
        firstName: z.string(),
        lastName: z.string()
    }).optional(),
    accessToken: z.string().optional()
});

export const zUpdateDossierControllerRunBody = z.object({
    dossierTemplateId: z.string().optional(),
    purpose: z.string().optional(),
    modelId: z.string().optional(),
    name: z.string().optional(),
    language: z.enum([
        'en_GB',
        'es_ES',
        'pt_PT'
    ]).optional(),
    filledFields: z.record(z.string(), z.unknown()).optional(),
    validityFrom: z.string().optional(),
    validityTo: z.string().optional(),
    accessToken: z.string().optional()
});

export const zUpdateDossierControllerRunPath = z.object({
    caseFileId: z.string(),
    dossierId: z.string()
});

export const zUpdateDossierControllerRunResponse = z.void();

export const zDeleteDossierEvidenceControllerRunPath = z.object({
    dossierEvidenceGroupId: z.string(),
    dossierId: z.string(),
    caseFileId: z.string(),
    dossierEvidenceId: z.string()
});

export const zDeleteDossierEvidenceControllerRunResponse = z.void();

export const zShowDossierEvidenceControllerRunPath = z.object({
    dossierEvidenceGroupId: z.string(),
    dossierId: z.string(),
    caseFileId: z.string(),
    dossierEvidenceId: z.string()
});

export const zShowDossierEvidenceControllerRunResponse = z.object({
    id: z.string(),
    title: z.string(),
    fileSize: z.number().optional(),
    fileName: z.string().optional(),
    type: z.string(),
    capturedAt: z.string(),
    dossierEvidenceGroupId: z.string(),
    evidenceId: z.string(),
    evidenceGroupId: z.string(),
    hash: z.string(),
    tspTimestamp: z.object({
        provider: z.string(),
        token: z.string(),
        date: z.string()
    }).optional(),
    tspTimestamps: z.array(z.object({
        provider: z.string(),
        token: z.string(),
        date: z.string()
    })),
    dltTimestamp: z.object({
        provider: z.string(),
        blockExplorerLink: z.string(),
        date: z.string()
    }).optional(),
    dltTimestamps: z.array(z.object({
        provider: z.string(),
        blockExplorerLink: z.string(),
        date: z.string()
    })),
    custodyType: z.string()
});

export const zUpdateDossierEvidenceControllerRunBody = z.object({
    title: z.string().optional()
});

export const zUpdateDossierEvidenceControllerRunPath = z.object({
    dossierEvidenceGroupId: z.string(),
    dossierId: z.string(),
    caseFileId: z.string(),
    dossierEvidenceId: z.string()
});

export const zUpdateDossierEvidenceControllerRunResponse = z.void();

export const zDeleteDossierEvidenceGroupControllerRunPath = z.object({
    dossierId: z.string(),
    caseFileId: z.string(),
    dossierEvidenceGroupId: z.string()
});

export const zDeleteDossierEvidenceGroupControllerRunResponse = z.void();

export const zShowDossierEvidenceGroupControllerRunPath = z.object({
    dossierId: z.string(),
    caseFileId: z.string(),
    dossierEvidenceGroupId: z.string()
});

export const zShowDossierEvidenceGroupControllerRunResponse = z.object({
    id: z.string(),
    code: z.string(),
    name: z.string(),
    evidencesCount: z.number(),
    createdAt: z.string(),
    type: z.string(),
    revised: z.boolean(),
    description: z.string().optional(),
    evidenceGroup: z.object({
        id: z.string(),
        name: z.string(),
        code: z.string(),
        evidenceMetadataId: z.string().optional()
    }),
    caseFile: z.object({
        id: z.string(),
        name: z.string(),
        code: z.string()
    })
});

export const zUpdateDossierEvidenceGroupControllerRunBody = z.object({
    id: z.string(),
    name: z.string().optional(),
    description: z.string().optional(),
    revised: z.boolean().optional()
});

export const zUpdateDossierEvidenceGroupControllerRunPath = z.object({
    dossierId: z.string(),
    caseFileId: z.string(),
    dossierEvidenceGroupId: z.string()
});

export const zUpdateDossierEvidenceGroupControllerRunResponse = z.void();

export const zLinkDossierEvidencesControllerRunBody = z.object({
    ids: z.array(z.uuid())
});

export const zLinkDossierEvidencesControllerRunPath = z.object({
    caseFileId: z.string(),
    dossierId: z.string(),
    caseFileToLinkId: z.string()
});

export const zListDossierEvidenceGroupsControllerRunPath = z.object({
    caseFileId: z.string(),
    dossierId: z.string()
});

export const zListDossierEvidenceGroupsControllerRunQuery = z.object({
    filter: z.object({
        evidenceGroupIds: z.array(z.uuid()).optional(),
        dossierId: z.uuid().optional(),
        search: z.string().optional(),
        type: z.enum([
            'FILE',
            'PHOTO',
            'VIDEO',
            'WEB_PLUGIN'
        ]).optional(),
        revised: z.boolean().optional(),
        originalCreatedAtFrom: z.string().optional(),
        originalCreatedAtUntil: z.string().optional(),
        id: z.string().optional()
    }).optional(),
    order: z.object({
        originalCreatedAt: z.enum(['ASC', 'DESC']).optional(),
        createdAt: z.enum(['ASC', 'DESC']).optional()
    }).optional(),
    page: z.object({
        number: z.number().gte(1).default(1),
        size: z.number().gte(0).lte(100).default(20)
    }).optional()
});

export const zListDossierEvidenceGroupsControllerRunResponse = z.object({
    data: z.array(z.object({
        id: z.string(),
        code: z.string(),
        name: z.string(),
        evidencesCount: z.number(),
        originalCreatedAt: z.string(),
        type: z.string(),
        revised: z.boolean()
    })).optional(),
    meta: z.object({
        totalElements: z.number().optional()
    }).optional()
});

export const zListDossierEvidencesControllerRunPath = z.object({
    caseFileId: z.string(),
    dossierId: z.string(),
    dossierEvidenceGroupId: z.string()
});

export const zListDossierEvidencesControllerRunQuery = z.object({
    filter: z.object({
        evidenceIds: z.array(z.uuid()).optional(),
        dossierId: z.uuid().optional(),
        dossierEvidenceGroupId: z.uuid().optional(),
        capturedFrom: z.string().optional(),
        capturedUntil: z.string().optional(),
        title: z.string().optional(),
        id: z.string().optional()
    }).optional(),
    order: z.object({
        capturedAt: z.enum(['ASC', 'DESC']).optional(),
        createdAt: z.enum(['ASC', 'DESC']).optional()
    }).optional(),
    page: z.object({
        number: z.number().gte(1).default(1),
        size: z.number().gte(0).lte(100).default(20)
    }).optional()
});

export const zListDossierEvidencesControllerRunResponse = z.object({
    data: z.array(z.object({
        id: z.string(),
        title: z.string(),
        fileSize: z.number().optional(),
        fileName: z.string().optional(),
        type: z.string(),
        capturedAt: z.string(),
        custodyType: z.string(),
        dossierEvidenceGroupId: z.string()
    })).optional(),
    meta: z.object({
        totalElements: z.number().optional()
    }).optional()
});

export const zListDossierEvidencesToLinkControllerRunPath = z.object({
    caseFileId: z.string(),
    dossierId: z.string(),
    caseFileToLinkId: z.string()
});

export const zListDossierEvidencesToLinkControllerRunQuery = z.object({
    filter: z.object({
        title: z.string().optional(),
        caseFileId: z.uuid().optional(),
        ids: z.array(z.uuid()).optional(),
        evidenceGroupIds: z.array(z.uuid()).optional(),
        capturedFrom: z.iso.datetime().optional(),
        capturedUntil: z.iso.datetime().optional(),
        relevant: z.boolean().optional(),
        id: z.string().optional()
    }).optional(),
    order: z.object({
        capturedAt: z.enum(['ASC', 'DESC']).optional(),
        evidenceGroupName: z.enum(['ASC', 'DESC']).optional(),
        createdAt: z.enum(['ASC', 'DESC']).optional()
    }).optional(),
    page: z.object({
        number: z.number().gte(1).default(1),
        size: z.number().gte(0).lte(100).default(20)
    }).optional()
});

export const zListDossierEvidencesToLinkControllerRunResponse = z.object({
    data: z.array(z.object({
        id: z.string(),
        title: z.string().optional(),
        fileSize: z.number().optional(),
        fileName: z.string(),
        capturedAt: z.string(),
        relevant: z.boolean(),
        custodyType: z.string(),
        evidenceGroup: z.object({
            id: z.string(),
            code: z.string(),
            name: z.string(),
            type: z.enum([
                'FILE',
                'PHOTO',
                'VIDEO',
                'WEB_PLUGIN'
            ]),
            caseFileId: z.string()
        }),
        linked: z.boolean()
    })).optional(),
    meta: z.object({
        totalElements: z.number().optional()
    }).optional()
});

export const zListDossierRecallRequestsControllerRunPath = z.object({
    caseFileId: z.string(),
    dossierId: z.string()
});

export const zListDossierRecallRequestsControllerRunQuery = z.object({
    filter: z.object({
        id: z.string().optional(),
        email: z.string().optional(),
        resolved: z.boolean().optional()
    }).optional(),
    order: z.object({
        createdAt: z.enum(['ASC', 'DESC']).optional()
    }).optional(),
    page: z.object({
        number: z.number().gte(1).default(1),
        size: z.number().gte(0).lte(100).default(20)
    }).optional()
});

export const zListDossierRecallRequestsControllerRunResponse = z.object({
    data: z.array(z.object({
        id: z.string(),
        dossierId: z.string(),
        firstName: z.string(),
        lastName: z.string(),
        phoneNumber: z.string().optional(),
        email: z.string(),
        reason: z.string(),
        createdAt: z.string()
    })).optional(),
    meta: z.object({
        totalElements: z.number().optional()
    }).optional()
});

export const zShowDossierDocumentUrlControllerRunPath = z.object({
    caseFileId: z.string(),
    dossierId: z.string()
});

export const zShowDossierDocumentUrlControllerRunResponse = z.object({
    documentUrl: z.string()
});

export const zShowDossierEvidenceDownloadUrlControllerRunPath = z.object({
    dossierEvidenceGroupId: z.string(),
    dossierId: z.string(),
    caseFileId: z.string(),
    dossierEvidenceId: z.string()
});

export const zShowDossierEvidenceDownloadUrlControllerRunResponse = z.object({
    downloadFileUrl: z.string()
});

export const zShowDossierEvidenceThumbnailControllerRunPath = z.object({
    dossierEvidenceGroupId: z.string(),
    dossierId: z.string(),
    caseFileId: z.string(),
    dossierEvidenceId: z.string(),
    size: z.string()
});

export const zShowDossierEvidenceThumbnailControllerRunResponse = z.object({
    url: z.string()
});

export const zShowDossierPackageUrlControllerRunPath = z.object({
    caseFileId: z.string(),
    dossierId: z.string()
});

export const zShowDossierPackageUrlControllerRunResponse = z.object({
    packageUrl: z.string()
});

export const zShowDossierPreviewControllerRunPath = z.object({
    caseFileId: z.string(),
    dossierId: z.string()
});

export const zShowDossierPreviewControllerRunResponse = z.record(z.string(), z.unknown());

export const zShowEvidenceWithLinkedToDossiersControllerRunPath = z.object({
    caseFileId: z.string(),
    evidenceGroupId: z.string(),
    id: z.string()
});

export const zShowEvidenceWithLinkedToDossiersControllerRunResponse = z.object({
    id: z.string(),
    linkedToDossiers: z.boolean()
});

export const zUpdateDossierVisibilityControllerRunBody = z.object({
    visibility: z.enum([
        'ACCESSIBLE',
        'PENDING_RECALL',
        'RECALLED'
    ])
});

export const zUpdateDossierVisibilityControllerRunPath = z.object({
    caseFileId: z.string(),
    dossierId: z.string()
});

export const zUpdateDossierVisibilityControllerRunResponse = z.void();

export const zListDossierTemplatesControllerRunQuery = z.object({
    page: z.object({
        number: z.number().gte(1).default(1),
        size: z.number().gte(0).lte(100).default(20)
    }).optional()
});

export const zListDossierTemplatesControllerRunResponse = z.object({
    data: z.array(z.object({
        id: z.string(),
        index: z.number(),
        requiresPurpose: z.boolean(),
        translations: z.array(z.object({
            id: z.string(),
            name: z.string(),
            language: z.string(),
            tipsDescription: z.string(),
            tipsList: z.array(z.string()),
            purposeDossier: z.string()
        }))
    })).optional(),
    meta: z.object({
        totalElements: z.number().optional()
    }).optional()
});

export const zCloseEvidenceGroupControllerRunBody = z.object({
    evidencesCount: z.number().gte(1),
    deviceModel: z.string().optional(),
    deviceManufacturer: z.string().optional(),
    deviceOS: z.string().optional(),
    latitudeLocation: z.string().optional(),
    longitudeLocation: z.string().optional(),
    altitudeLocation: z.string().optional(),
    locationAccuracy: z.string().optional(),
    userAgent: z.string().optional(),
    webUrl: z.string().optional(),
    attestation: z.object({
        provider: z.enum(['PlayIntegrity', 'AppAttest']),
        app: z.enum(['App', 'AppPro']),
        token: z.string().optional(),
        keyId: z.string().optional(),
        assertion: z.string().optional()
    }).optional()
});

export const zCloseEvidenceGroupControllerRunPath = z.object({
    caseFileId: z.string(),
    id: z.string()
});

export const zCreateEvidenceControllerRunBody = z.object({
    id: z.uuid(),
    hash: z.string(),
    title: z.string().max(128),
    evidenceGroupId: z.uuid(),
    caseFileId: z.uuid(),
    custodyType: z.enum(['INTERNAL', 'EXTERNAL']).default('EXTERNAL'),
    fileName: z.string().optional()
});

export const zCreateEvidenceControllerRunResponse = z.object({
    uploadFileUrl: z.string().optional(),
    expiration: z.string().optional()
});

export const zCreateEvidenceGroupControllerRunBody = z.object({
    id: z.uuid(),
    evidenceType: z.enum([
        'FILE',
        'PHOTO',
        'VIDEO',
        'WEB_PLUGIN'
    ]),
    name: z.string().max(64),
    description: z.string().max(160).optional(),
    caseFileId: z.uuid(),
    attestation: z.object({
        provider: z.enum(['PlayIntegrity', 'AppAttest']),
        app: z.enum(['App', 'AppPro']),
        token: z.string().optional(),
        keyId: z.string().optional(),
        assertion: z.string().optional()
    }).optional()
});

export const zDeleteEvidenceControllerRunPath = z.object({
    caseFileId: z.string(),
    evidenceGroupId: z.string(),
    id: z.string()
});

export const zDeleteEvidenceControllerRunResponse = z.void();

export const zShowEvidenceControllerRunPath = z.object({
    caseFileId: z.string(),
    evidenceGroupId: z.string(),
    id: z.string()
});

export const zShowEvidenceControllerRunResponse = z.object({
    tspTimestamp: z.object({
        provider: z.string(),
        token: z.string(),
        date: z.string()
    }).optional(),
    dltTimestamp: z.object({
        provider: z.string(),
        blockExplorerLink: z.string(),
        date: z.string()
    }).optional(),
    id: z.string(),
    title: z.string().optional(),
    fileSize: z.number().optional(),
    fileName: z.string(),
    capturedAt: z.string(),
    status: z.string(),
    hash: z.string(),
    relevant: z.boolean(),
    favorite: z.boolean(),
    custodyType: z.string(),
    tspTimestamps: z.array(z.object({
        provider: z.string(),
        token: z.string(),
        date: z.string()
    })),
    dltTimestamps: z.array(z.object({
        provider: z.string(),
        blockExplorerLink: z.string(),
        date: z.string()
    }))
});

export const zUpdateEvidenceControllerRunBody = z.object({
    title: z.string().max(128).optional(),
    relevant: z.boolean().optional()
});

export const zUpdateEvidenceControllerRunPath = z.object({
    evidenceGroupId: z.string(),
    caseFileId: z.string(),
    id: z.string()
});

export const zUpdateEvidenceControllerRunResponse = z.void();

export const zDiscardEvidenceGroupControllerRunPath = z.object({
    caseFileId: z.string(),
    id: z.string()
});

export const zDiscardEvidenceGroupControllerRunResponse = z.void();

export const zShowEvidenceGroupControllerRunPath = z.object({
    caseFileId: z.string(),
    id: z.string()
});

export const zShowEvidenceGroupControllerRunResponse = z.object({
    id: z.string(),
    caseFileId: z.string(),
    code: z.string(),
    name: z.string(),
    description: z.string().optional(),
    type: z.string(),
    status: z.string(),
    evidenceStats: z.object({
        inProcess: z.number(),
        failed: z.number(),
        completed: z.number(),
        total: z.number()
    }),
    evidenceMetadataId: z.string().optional(),
    createdBy: z.object({
        id: z.string(),
        firstName: z.string(),
        lastName: z.string()
    }).optional(),
    createdAt: z.string()
});

export const zUpdateEvidenceGroupControllerRunBody = z.object({
    name: z.string().max(64),
    description: z.string().max(160).optional()
});

export const zUpdateEvidenceGroupControllerRunPath = z.object({
    caseFileId: z.string(),
    id: z.string()
});

export const zUpdateEvidenceGroupControllerRunResponse = z.void();

export const zDownloadUrlEvidenceControllerRunPath = z.object({
    caseFileId: z.string(),
    evidenceGroupId: z.string(),
    id: z.string()
});

export const zDownloadUrlEvidenceControllerRunResponse = z.object({
    downloadFileUrl: z.string()
});

export const zListEvidenceGroupsControllerRunPath = z.object({
    caseFileId: z.string()
});

export const zListEvidenceGroupsControllerRunQuery = z.object({
    filter: z.object({
        ids: z.array(z.uuid()).optional(),
        caseFileId: z.string().optional(),
        createdById: z.string().optional(),
        name: z.string().optional(),
        createdFrom: z.iso.datetime().optional(),
        createdUntil: z.iso.datetime().optional(),
        status: z.enum([
            'OPEN',
            'CLOSED',
            'CLOSING'
        ]).optional(),
        type: z.enum([
            'FILE',
            'PHOTO',
            'VIDEO',
            'WEB_PLUGIN'
        ]).optional(),
        id: z.string().optional()
    }).optional(),
    order: z.object({
        createdAt: z.enum(['ASC', 'DESC']).optional()
    }).optional(),
    page: z.object({
        number: z.number().gte(1).default(1),
        size: z.number().gte(0).lte(100).default(20)
    }).optional()
});

export const zListEvidenceGroupsControllerRunResponse = z.object({
    data: z.array(z.object({
        id: z.string(),
        caseFileId: z.string(),
        code: z.string(),
        name: z.string(),
        type: z.string(),
        status: z.string(),
        evidenceStats: z.object({
            inProcess: z.number(),
            failed: z.number(),
            completed: z.number(),
            total: z.number()
        }),
        createdBy: z.object({
            id: z.string(),
            firstName: z.string(),
            lastName: z.string()
        }).optional(),
        createdAt: z.string()
    })).optional(),
    meta: z.object({
        totalElements: z.number().optional()
    }).optional()
});

export const zListEvidencesByCaseFileControllerRunPath = z.object({
    caseFileId: z.string()
});

export const zListEvidencesByCaseFileControllerRunQuery = z.object({
    filter: z.object({
        ids: z.array(z.uuid()).optional(),
        caseFileId: z.string().optional(),
        evidenceGroupIds: z.array(z.string()).optional(),
        evidenceGroupTypes: z.array(z.enum([
            'FILE',
            'PHOTO',
            'VIDEO',
            'WEB_PLUGIN'
        ])).optional(),
        title: z.string().optional(),
        status: z.enum([
            'COMPLETED',
            'IN_PROCESS',
            'ERROR'
        ]).optional(),
        capturedFrom: z.iso.datetime().optional(),
        capturedUntil: z.iso.datetime().optional(),
        relevant: z.boolean().optional(),
        favorite: z.boolean().optional(),
        collectionMetadata: z.boolean().optional(),
        id: z.string().optional()
    }).optional(),
    order: z.object({
        capturedAt: z.enum(['ASC', 'DESC']).optional(),
        evidenceGroupName: z.enum(['ASC', 'DESC']).optional()
    }).optional(),
    page: z.object({
        number: z.number().gte(1).default(1),
        size: z.number().gte(0).lte(100).default(20)
    }).optional()
});

export const zListEvidencesByCaseFileControllerRunResponse = z.object({
    data: z.array(z.object({
        id: z.string(),
        title: z.string().optional(),
        fileSize: z.number().optional(),
        fileName: z.string(),
        capturedAt: z.string(),
        status: z.string(),
        hash: z.string(),
        relevant: z.boolean(),
        favorite: z.boolean(),
        custodyType: z.string(),
        evidenceGroup: z.object({
            id: z.string(),
            code: z.string(),
            name: z.string(),
            type: z.string()
        })
    })).optional(),
    meta: z.object({
        totalElements: z.number().optional()
    }).optional()
});

export const zListEvidencesControllerRunPath = z.object({
    caseFileId: z.string(),
    evidenceGroupId: z.string()
});

export const zListEvidencesControllerRunQuery = z.object({
    filter: z.object({
        ids: z.array(z.uuid()).optional(),
        caseFileId: z.string().optional(),
        evidenceGroupIds: z.array(z.string()).optional(),
        evidenceGroupTypes: z.array(z.enum([
            'FILE',
            'PHOTO',
            'VIDEO',
            'WEB_PLUGIN'
        ])).optional(),
        title: z.string().optional(),
        status: z.enum([
            'COMPLETED',
            'IN_PROCESS',
            'ERROR'
        ]).optional(),
        capturedFrom: z.iso.datetime().optional(),
        capturedUntil: z.iso.datetime().optional(),
        relevant: z.boolean().optional(),
        favorite: z.boolean().optional(),
        collectionMetadata: z.boolean().optional(),
        id: z.string().optional()
    }).optional(),
    order: z.object({
        capturedAt: z.enum(['ASC', 'DESC']).optional(),
        evidenceGroupName: z.enum(['ASC', 'DESC']).optional()
    }).optional(),
    page: z.object({
        number: z.number().gte(1).default(1),
        size: z.number().gte(0).lte(100).default(20)
    }).optional()
});

export const zListEvidencesControllerRunResponse = z.object({
    data: z.array(z.object({
        id: z.string(),
        title: z.string().optional(),
        fileSize: z.number().optional(),
        fileName: z.string(),
        capturedAt: z.string(),
        status: z.string(),
        hash: z.string(),
        relevant: z.boolean(),
        favorite: z.boolean(),
        custodyType: z.string(),
        evidenceGroup: z.object({
            id: z.string(),
            code: z.string(),
            name: z.string(),
            type: z.string()
        })
    })).optional(),
    meta: z.object({
        totalElements: z.number().optional()
    }).optional()
});

export const zListEvidenceTypesControllerRunQuery = z.object({
    filter: z.object({
        code: z.enum([
            'FILE',
            'PHOTO',
            'VIDEO',
            'WEB_PLUGIN'
        ]).optional(),
        id: z.string().optional()
    }).optional(),
    order: z.object({
        createdAt: z.enum(['ASC', 'DESC']).optional(),
        index: z.enum(['ASC', 'DESC']).optional()
    }).optional(),
    page: z.object({
        number: z.number().gte(1).default(1),
        size: z.number().gte(0).lte(100).default(20)
    }).optional()
});

export const zListEvidenceTypesControllerRunResponse = z.object({
    data: z.array(z.object({
        id: z.string(),
        code: z.string(),
        index: z.number(),
        translations: z.array(z.object({
            id: z.string(),
            name: z.string(),
            language: z.string(),
            tipsDescription: z.string(),
            tipsList: z.array(z.string()),
            purposeDossier: z.string()
        }))
    })).optional(),
    meta: z.object({
        totalElements: z.number().optional()
    }).optional()
});

export const zListTimestampTypesControllerRunQuery = z.object({
    filter: z.object({
        id: z.string().optional()
    }).optional(),
    order: z.object({
        createdAt: z.enum(['ASC', 'DESC']).optional(),
        index: z.enum(['ASC', 'DESC']).optional()
    }).optional(),
    page: z.object({
        number: z.number().gte(1).default(1),
        size: z.number().gte(0).lte(100).default(20)
    }).optional()
});

export const zListTimestampTypesControllerRunResponse = z.object({
    data: z.array(z.object({
        id: z.string(),
        category: z.enum(['TSP', 'DLT']),
        index: z.number(),
        translations: z.array(z.object({
            id: z.string(),
            name: z.string(),
            language: z.string(),
            tipsDescription: z.string(),
            tipsList: z.array(z.string()),
            purposeDossier: z.string()
        }))
    })).optional(),
    meta: z.object({
        totalElements: z.number().optional()
    }).optional()
});

export const zProcessEvidenceGroupsCallbackControllerRunBody = z.object({
    operation: z.string(),
    result: z.enum(['OK', 'KO']),
    data: z.object({
        evidenceGroupId: z.uuid(),
        caseFileId: z.uuid()
    })
});

export const zProcessEvidenceGroupsCallbackControllerRunResponse = z.void();

export const zProcessEvidencesCallbackControllerRunBody = z.object({
    operation: z.string(),
    result: z.enum(['OK', 'KO']),
    data: z.object({
        evidenceId: z.uuid(),
        evidenceGroupId: z.uuid(),
        caseFileId: z.uuid()
    })
});

export const zProcessEvidencesCallbackControllerRunResponse = z.void();

export const zThumbnailEvidenceControllerRunPath = z.object({
    caseFileId: z.string(),
    evidenceGroupId: z.string(),
    id: z.string(),
    size: z.string()
});

export const zThumbnailEvidenceControllerRunResponse = z.object({
    url: z.string()
});

export const zUpdateFavoriteEvidenceControllerRunBody = z.object({
    favorite: z.boolean()
});

export const zUpdateFavoriteEvidenceControllerRunPath = z.object({
    evidenceGroupId: z.string(),
    caseFileId: z.string(),
    id: z.string()
});

export const zUpdateFavoriteEvidenceControllerRunResponse = z.void();

export const zUploadUrlEvidenceControllerRunBody = z.object({
    hash: z.string(),
    fileName: z.string()
});

export const zUploadUrlEvidenceControllerRunPath = z.object({
    caseFileId: z.string(),
    evidenceGroupId: z.string(),
    id: z.string()
});

export const zUploadUrlEvidenceControllerRunResponse = z.object({
    uploadFileUrl: z.string(),
    expiration: z.string()
});

export const zCancelLargeEvidenceUploadControllerRunPath = z.object({
    caseFileId: z.string(),
    evidenceGroupId: z.string(),
    id: z.string()
});

export const zCancelLargeEvidenceUploadControllerRunResponse = z.void();

export const zCreateEvidenceGroupCloseRequestControllerRunBody = z.object({
    id: z.uuid(),
    userAgent: z.string().max(2000).optional()
});

export const zCreateEvidenceGroupCloseRequestControllerRunPath = z.object({
    caseFileId: z.string(),
    evidenceGroupId: z.string()
});

export const zListLargeEvidenceUploadsControllerRunPath = z.object({
    caseFileId: z.string(),
    evidenceGroupId: z.string()
});

export const zListLargeEvidenceUploadsControllerRunQuery = z.object({
    page: z.object({
        number: z.number().gte(1).default(1),
        size: z.number().gte(0).lte(100).default(20)
    }).optional()
});

export const zListLargeEvidenceUploadsControllerRunResponse = z.object({
    data: z.array(z.object({
        id: z.string(),
        fileName: z.string(),
        chunkSizeMB: z.number(),
        totalSizeMB: z.number(),
        biggestUploadedOffset: z.number()
    })).optional(),
    meta: z.object({
        totalElements: z.number().optional()
    }).optional()
});

export const zCreateLargeEvidenceUploadControllerRunBody = z.object({
    id: z.uuid(),
    evidenceId: z.uuid(),
    totalSizeMB: z.number().gte(1),
    title: z.string().max(128),
    fileName: z.string(),
    capturedAt: z.string()
});

export const zCreateLargeEvidenceUploadControllerRunPath = z.object({
    caseFileId: z.string(),
    evidenceGroupId: z.string()
});

export const zListAndCreateEvidencePendingOffsetsControllerRunPath = z.object({
    caseFileId: z.string(),
    evidenceGroupId: z.string(),
    id: z.string()
});

export const zListAndCreateEvidencePendingOffsetsControllerRunQuery = z.object({
    count: z.number(),
    page: z.object({
        number: z.number().gte(1).default(1),
        size: z.number().gte(0).lte(100).default(20)
    }).optional()
});

export const zListAndCreateEvidencePendingOffsetsControllerRunResponse = z.object({
    data: z.array(z.object({
        id: z.string(),
        largeEvidenceUploadId: z.string(),
        offset: z.number()
    })).optional(),
    meta: z.object({
        totalElements: z.number().optional()
    }).optional()
});

export const zNotifyEvidenceUploadedOffsetControllerRunPath = z.object({
    caseFileId: z.string(),
    evidenceGroupId: z.string(),
    largeEvidenceUploadId: z.string(),
    id: z.string()
});

export const zNotifyEvidenceUploadedOffsetControllerRunResponse = z.void();

export const zShowEvidencePendingOffsetUploadUrlControllerRunPath = z.object({
    caseFileId: z.string(),
    evidenceGroupId: z.string(),
    largeEvidenceUploadId: z.string(),
    id: z.string()
});

export const zShowEvidencePendingOffsetUploadUrlControllerRunResponse = z.object({
    url: z.string()
});

export const zListNotificationCertificatesControllerRunPath = z.object({
    caseFileId: z.string(),
    notificationRequestId: z.string(),
    receiverId: z.string()
});

export const zListNotificationCertificatesControllerRunQuery = z.object({
    filter: z.object({
        partial: z.boolean(),
        language: z.enum(['en_GB', 'es_ES']).optional(),
        id: z.string().optional()
    }).optional(),
    order: z.object({
        createdAt: z.enum(['ASC', 'DESC']).optional()
    }).optional(),
    page: z.object({
        number: z.number().gte(1).default(1),
        size: z.number().gte(0).lte(100).default(20)
    }).optional()
});

export const zListNotificationCertificatesControllerRunResponse = z.object({
    data: z.array(z.object({
        id: z.string(),
        notificationRequestId: z.string(),
        receiverId: z.string(),
        partial: z.boolean(),
        status: z.enum([
            'CERTIFYING',
            'DRAFT',
            'CERTIFIED'
        ]),
        createdAt: z.string(),
        certifiedAt: z.string().optional(),
        language: z.enum(['en_GB', 'es_ES'])
    })).optional(),
    meta: z.object({
        totalElements: z.number().optional()
    }).optional()
});

export const zCreateNotificationCertificateControllerRunBody = z.object({
    id: z.uuid(),
    language: z.enum(['en_GB', 'es_ES']).optional()
});

export const zCreateNotificationCertificateControllerRunPath = z.object({
    caseFileId: z.string(),
    notificationRequestId: z.string(),
    receiverId: z.string()
});

export const zProcessNotificationCertificatesCallbackControllerRunBody = z.object({
    eventType: z.string(),
    data: z.object({
        reportId: z.string()
    })
});

export const zProcessNotificationCertificatesCallbackControllerRunResponse = z.void();

export const zShowNotificationCertificateDocumentUrlControllerRunPath = z.object({
    caseFileId: z.string(),
    notificationRequestId: z.string(),
    receiverId: z.string(),
    certificateId: z.string()
});

export const zShowNotificationCertificateDocumentUrlControllerRunResponse = z.object({
    documentUrl: z.string()
});

export const zShowNotificationCertificatePackageUrlControllerRunPath = z.object({
    caseFileId: z.string(),
    notificationRequestId: z.string(),
    receiverId: z.string(),
    certificateId: z.string()
});

export const zShowNotificationCertificatePackageUrlControllerRunResponse = z.object({
    packageUrl: z.string()
});

export const zActivateNotificationRequestControllerRunPath = z.object({
    caseFileId: z.string(),
    notificationRequestId: z.string()
});

export const zCreateMassiveNotificationReceiversControllerRunBody = z.object({
    receivers: z.array(z.object({
        id: z.string(),
        firstName: z.string(),
        lastName: z.string(),
        email: z.string(),
        phoneNumber: z.string().optional(),
        phonePrefix: z.string().optional()
    }))
});

export const zCreateMassiveNotificationReceiversControllerRunPath = z.object({
    caseFileId: z.string(),
    notificationRequestId: z.string()
});

export const zListNotificationDocumentsControllerRunPath = z.object({
    caseFileId: z.string(),
    notificationRequestId: z.string()
});

export const zListNotificationDocumentsControllerRunQuery = z.object({
    filter: z.object({
        fileName: z.string().optional(),
        status: z.enum(['PENDING', 'READY_TO_SEND']).optional(),
        id: z.string().optional()
    }).optional(),
    order: z.object({
        createdAt: z.enum(['ASC', 'DESC']).optional()
    }).optional(),
    page: z.object({
        number: z.number().gte(1).default(1),
        size: z.number().gte(0).lte(100).default(20)
    }).optional()
});

export const zCreateNotificationDocumentControllerRunBody = z.object({
    id: z.uuid(),
    fileName: z.string(),
    hash: z.string(),
    fileSize: z.number().optional()
});

export const zCreateNotificationDocumentControllerRunPath = z.object({
    caseFileId: z.string(),
    notificationRequestId: z.string()
});

export const zCreateNotificationDocumentControllerRunResponse = z.object({
    url: z.string()
});

export const zListNotificationReceiversControllerRunPath = z.object({
    caseFileId: z.string(),
    notificationRequestId: z.string()
});

export const zListNotificationReceiversControllerRunQuery = z.object({
    filter: z.object({
        id: z.string().optional()
    }).optional(),
    order: z.object({
        createdAt: z.enum(['ASC', 'DESC']).optional(),
        email: z.enum(['ASC', 'DESC']).optional()
    }).optional(),
    page: z.object({
        number: z.number().gte(1).default(1),
        size: z.number().gte(0).lte(100).default(20)
    }).optional()
});

export const zListNotificationReceiversControllerRunResponse = z.object({
    data: z.array(z.object({
        id: z.string(),
        notificationRequestId: z.string(),
        status: z.enum([
            'INVALID',
            'READY_TO_SEND',
            'SENT',
            'READ',
            'ANSWERED',
            'ERROR'
        ]),
        validationError: z.enum([
            'TAKEN',
            'IS_DEFINED',
            'IS_INVALID'
        ]).optional(),
        answer: z.string().optional(),
        firstName: z.string().optional(),
        lastName: z.string().optional(),
        email: z.string().optional(),
        phonePrefix: z.string().optional(),
        phoneNumber: z.string().optional(),
        statusUpdatedAt: z.string(),
        otpRequired: z.boolean(),
        sendWaUrl: z.boolean(),
        emailBounced: z.boolean(),
        createdAt: z.string()
    })).optional(),
    meta: z.object({
        totalElements: z.number().optional()
    }).optional()
});

export const zCreateNotificationReceiverControllerRunBody = z.object({
    id: z.string(),
    firstName: z.string(),
    lastName: z.string(),
    email: z.string(),
    phoneNumber: z.string().optional(),
    phonePrefix: z.string().optional(),
    otpRequired: z.boolean().optional(),
    sendWaUrl: z.boolean().optional()
});

export const zCreateNotificationReceiverControllerRunPath = z.object({
    caseFileId: z.string(),
    notificationRequestId: z.string()
});

export const zCreateNotificationRequestControllerRunBody = z.object({
    id: z.uuid(),
    type: z.enum([
        'NO_RESPONSE',
        'ACCEPTED_OR_NOT',
        'RECEIVED_AGREE'
    ]).optional(),
    subject: z.string().max(100),
    content: z.string(),
    language: z.enum(['en_GB', 'es_ES']),
    otpByDefault: z.boolean().optional(),
    sendWaUrlByDefault: z.boolean().optional()
});

export const zCreateNotificationRequestControllerRunPath = z.object({
    caseFileId: z.string()
});

export const zDeleteInvalidNotificationReceiversControllerRunPath = z.object({
    caseFileId: z.string(),
    notificationRequestId: z.string()
});

export const zDeleteNotificationDocumentControllerRunPath = z.object({
    caseFileId: z.string(),
    notificationRequestId: z.string(),
    documentId: z.string()
});

export const zDeleteNotificationReceiverControllerRunPath = z.object({
    caseFileId: z.string(),
    notificationRequestId: z.string(),
    receiverId: z.string()
});

export const zUpdateNotificationReceiverControllerRunBody = z.object({
    firstName: z.string().optional(),
    lastName: z.string().optional(),
    email: z.string().optional(),
    phonePrefix: z.string().optional(),
    phoneNumber: z.string().optional()
});

export const zUpdateNotificationReceiverControllerRunPath = z.object({
    caseFileId: z.string(),
    notificationRequestId: z.string(),
    receiverId: z.string()
});

export const zDeleteNotificationRequestControllerRunPath = z.object({
    caseFileId: z.string(),
    notificationRequestId: z.string()
});

export const zShowNotificationRequestControllerRunPath = z.object({
    caseFileId: z.string(),
    notificationRequestId: z.string()
});

export const zShowNotificationRequestControllerRunResponse = z.object({
    id: z.string(),
    code: z.string(),
    subject: z.string(),
    content: z.string(),
    language: z.enum(['en_GB', 'es_ES']),
    status: z.enum([
        'CREATING',
        'DRAFT',
        'IN_PROCESS',
        'SENT',
        'PARTIALLY_READ',
        'FULLY_READ',
        'PARTIALLY_ANSWERED',
        'FULLY_ANSWERED'
    ]),
    type: z.enum([
        'NO_RESPONSE',
        'ACCEPTED_OR_NOT',
        'RECEIVED_AGREE'
    ]),
    statusUpdatedAt: z.string(),
    sentAt: z.string().optional(),
    createdAt: z.string(),
    otpByDefault: z.boolean(),
    sendWaUrlByDefault: z.boolean(),
    caseFile: z.object({
        id: z.string(),
        useCaseId: z.string(),
        name: z.string(),
        code: z.string(),
        ownerId: z.string()
    }),
    owner: z.object({
        id: z.string(),
        firstName: z.string(),
        lastName: z.string(),
        role: z.string(),
        email: z.string()
    }),
    createdBy: z.object({
        id: z.string(),
        firstName: z.string(),
        lastName: z.string(),
        role: z.string(),
        email: z.string()
    }).optional(),
    receiverStats: z.object({
        total: z.number(),
        bounced: z.number(),
        valid: z.number()
    })
});

export const zUpdateNotificationRequestControllerRunBody = z.object({
    type: z.enum([
        'NO_RESPONSE',
        'ACCEPTED_OR_NOT',
        'RECEIVED_AGREE'
    ]).optional(),
    subject: z.string().max(100).optional(),
    content: z.string().optional(),
    language: z.enum(['en_GB', 'es_ES']).optional()
});

export const zUpdateNotificationRequestControllerRunPath = z.object({
    caseFileId: z.string(),
    notificationRequestId: z.string()
});

export const zDuplicateNotificationRequestControllerRunBody = z.object({
    caseFileId: z.uuid().optional(),
    id: z.uuid(),
    subject: z.string().max(100)
});

export const zDuplicateNotificationRequestControllerRunPath = z.object({
    caseFileId: z.string(),
    notificationRequestId: z.string()
});

export const zListNotificationRequestsControllerRunPath = z.object({
    userId: z.string()
});

export const zListNotificationRequestsControllerRunQuery = z.object({
    filter: z.object({
        status: z.enum([
            'CREATING',
            'DRAFT',
            'IN_PROCESS',
            'SENT',
            'PARTIALLY_READ',
            'FULLY_READ',
            'PARTIALLY_ANSWERED',
            'FULLY_ANSWERED'
        ]).optional(),
        statuses: z.array(z.enum([
            'CREATING',
            'DRAFT',
            'IN_PROCESS',
            'SENT',
            'PARTIALLY_READ',
            'FULLY_READ',
            'PARTIALLY_ANSWERED',
            'FULLY_ANSWERED'
        ])).optional(),
        search: z.string().optional(),
        caseFileIds: z.array(z.uuid()).optional(),
        receiversSearch: z.string().optional()
    }).optional(),
    order: z.object({
        createdAt: z.enum(['ASC', 'DESC']).optional()
    }).optional(),
    page: z.object({
        number: z.number().gte(1).default(1),
        size: z.number().gte(0).lte(100).default(20)
    }).optional()
});

export const zListNotificationRequestsControllerRunResponse = z.object({
    data: z.array(z.object({
        id: z.string(),
        code: z.string(),
        subject: z.string(),
        status: z.enum([
            'CREATING',
            'DRAFT',
            'IN_PROCESS',
            'SENT',
            'PARTIALLY_READ',
            'FULLY_READ',
            'PARTIALLY_ANSWERED',
            'FULLY_ANSWERED'
        ]),
        type: z.enum([
            'NO_RESPONSE',
            'ACCEPTED_OR_NOT',
            'RECEIVED_AGREE'
        ]),
        statusUpdatedAt: z.string(),
        createdAt: z.string(),
        sentAt: z.string().optional(),
        otpByDefault: z.boolean(),
        receiverStats: z.object({
            firstEmail: z.string(),
            total: z.number()
        }),
        sendWaUrlByDefault: z.boolean(),
        caseFile: z.object({
            id: z.string(),
            useCaseId: z.string(),
            name: z.string(),
            code: z.string()
        }),
        owner: z.object({
            id: z.string(),
            firstName: z.string(),
            lastName: z.string()
        }),
        createdBy: z.object({
            id: z.string(),
            firstName: z.string(),
            lastName: z.string()
        }).optional()
    })).optional(),
    meta: z.object({
        totalElements: z.number().optional()
    }).optional()
});

export const zProcessNotificationsCallbackControllerRunBody = z.object({
    eventType: z.string(),
    data: z.object({
        notificationId: z.string().optional(),
        notificationAttachmentId: z.string().optional()
    })
});

export const zProcessNotificationsCallbackControllerRunResponse = z.void();

export const zSendNotificationRequestControllerRunPath = z.object({
    caseFileId: z.string(),
    notificationRequestId: z.string()
});

export const zShowNotificationDocumentDownloadUrlControllerRunPath = z.object({
    caseFileId: z.string(),
    notificationRequestId: z.string(),
    documentId: z.string()
});

export const zShowNotificationDocumentDownloadUrlControllerRunResponse = z.object({
    downloadUrl: z.string()
});

export const zUpdateNotificationRequestCaseFileIdControllerRunBody = z.object({
    caseFileId: z.uuid()
});

export const zUpdateNotificationRequestCaseFileIdControllerRunPath = z.object({
    caseFileId: z.string(),
    notificationRequestId: z.string()
});

export const zListSignaturePartialCertificatesControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string(),
    documentId: z.string()
});

export const zListSignaturePartialCertificatesControllerRunQuery = z.object({
    filter: z.object({
        id: z.string().optional()
    }).optional(),
    order: z.object({
        createdAt: z.enum(['ASC', 'DESC']).optional()
    }).optional(),
    page: z.object({
        number: z.number().gte(1).default(1),
        size: z.number().gte(0).lte(100).default(20)
    }).optional()
});

export const zListSignaturePartialCertificatesControllerRunResponse = z.object({
    data: z.array(z.object({
        id: z.string(),
        requestId: z.string(),
        documentId: z.string(),
        status: z.enum([
            'CERTIFYING',
            'DRAFT',
            'CERTIFIED'
        ]),
        createdAt: z.string(),
        certifiedAt: z.string().optional()
    })).optional(),
    meta: z.object({
        totalElements: z.number().optional()
    }).optional()
});

export const zCreateSignaturePartialCertificateControllerRunBody = z.object({
    id: z.uuid()
});

export const zCreateSignaturePartialCertificateControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string(),
    documentId: z.string()
});

export const zProcessSignatureCertificatesCallbackControllerRunBody = z.object({
    operationType: z.enum(['REPORTS']),
    data: z.object({
        processId: z.uuid()
    })
});

export const zProcessSignatureCertificatesCallbackControllerRunResponse = z.void();

export const zShowSignatureCertificateDocumentUrlControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string(),
    documentId: z.string()
});

export const zShowSignatureCertificateDocumentUrlControllerRunResponse = z.object({
    documentUrl: z.string()
});

export const zShowSignatureCertificatePackageUrlControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string(),
    documentId: z.string()
});

export const zShowSignatureCertificatePackageUrlControllerRunResponse = z.object({
    packageUrl: z.string()
});

export const zShowSignatureCertificateSignaturesUrlControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string(),
    documentId: z.string()
});

export const zShowSignatureCertificateSignaturesUrlControllerRunResponse = z.object({
    signaturesUrl: z.string()
});

export const zShowSignatureDocumentSignedDocumentUrlControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string(),
    documentId: z.string()
});

export const zShowSignatureDocumentSignedDocumentUrlControllerRunResponse = z.object({
    signedDocumentUrl: z.string()
});

export const zShowSignaturePartialCertificateDocumentUrlControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string(),
    documentId: z.string(),
    certificateId: z.string()
});

export const zShowSignaturePartialCertificateDocumentUrlControllerRunResponse = z.object({
    documentUrl: z.string()
});

export const zShowSignaturePartialCertificatePackageUrlControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string(),
    documentId: z.string(),
    certificateId: z.string()
});

export const zShowSignaturePartialCertificatePackageUrlControllerRunResponse = z.object({
    packageUrl: z.string()
});

export const zShowSignaturePartialCertificateSignaturesUrlControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string(),
    documentId: z.string(),
    certificateId: z.string()
});

export const zShowSignaturePartialCertificateSignaturesUrlControllerRunResponse = z.object({
    signaturesUrl: z.string()
});

export const zActivateSignatureRequestControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string()
});

export const zCancelSignatureRequestControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string()
});

export const zCloseSignatureRequestControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string()
});

export const zCreateDocumentParticipantsControllerRunBody = z.object({
    participantIds: z.array(z.uuid()).max(100)
});

export const zCreateDocumentParticipantsControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string(),
    documentId: z.string()
});

export const zCreateMassiveSignatureParticipantsControllerRunBody = z.object({
    participants: z.array(z.object({
        id: z.string(),
        role: z.enum([
            'SIGNATORY',
            'OBSERVER',
            'VALIDATOR'
        ]),
        firstName: z.string(),
        lastName: z.string(),
        email: z.string(),
        phoneNumber: z.string().optional(),
        phonePrefix: z.string().optional()
    }))
});

export const zCreateMassiveSignatureParticipantsControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string()
});

export const zListSignatoryValidatorsControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string(),
    signatoryId: z.string()
});

export const zListSignatoryValidatorsControllerRunQuery = z.object({
    page: z.object({
        number: z.number().gte(1).default(1),
        size: z.number().gte(0).lte(100).default(20)
    }).optional()
});

export const zListSignatoryValidatorsControllerRunResponse = z.object({
    data: z.array(z.object({
        id: z.string(),
        email: z.string(),
        firstName: z.string(),
        lastName: z.string()
    })).optional(),
    meta: z.object({
        totalElements: z.number().optional()
    }).optional()
});

export const zCreateSignatoryValidatorsControllerRunBody = z.object({
    validatorIds: z.array(z.uuid()).max(100)
});

export const zCreateSignatoryValidatorsControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string(),
    signatoryId: z.string()
});

export const zListSignatureDocumentsControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string()
});

export const zListSignatureDocumentsControllerRunQuery = z.object({
    filter: z.object({
        status: z.enum([
            'PENDING',
            'READY_TO_SIGN',
            'PARTIALLY_SIGNED',
            'SIGNED',
            'REJECTED',
            'ERROR'
        ]).optional(),
        fileName: z.string().optional(),
        groupIds: z.array(z.uuid()).optional()
    }).optional(),
    order: z.object({
        createdAt: z.enum(['ASC', 'DESC']).optional(),
        groupIndex: z.enum(['ASC', 'DESC']).optional()
    }).optional(),
    page: z.object({
        number: z.number().gte(1).default(1),
        size: z.number().gte(0).lte(100).default(20)
    }).optional()
});

export const zListSignatureDocumentsControllerRunResponse = z.object({
    data: z.array(z.object({
        id: z.string(),
        requestId: z.string(),
        groupId: z.string().optional(),
        status: z.enum([
            'PENDING',
            'READY_TO_SIGN',
            'PARTIALLY_SIGNED',
            'SIGNED',
            'REJECTED',
            'ERROR'
        ]),
        title: z.string(),
        fileName: z.string(),
        fileSize: z.number().optional(),
        convertToPdf: z.boolean(),
        participantStats: z.object({
            signatories: z.number(),
            observers: z.number()
        }),
        signatoryStatusStats: z.object({
            pending: z.number(),
            readyToSign: z.number(),
            signed: z.number(),
            rejected: z.number()
        }),
        signatoryCoordinatesStats: z.object({
            defined: z.number(),
            missing: z.number()
        })
    })).optional(),
    meta: z.object({
        totalElements: z.number().optional()
    }).optional()
});

export const zCreateSignatureDocumentControllerRunBody = z.object({
    id: z.string(),
    groupId: z.string().optional(),
    hash: z.string(),
    title: z.string(),
    fileName: z.string(),
    fileSize: z.number().optional(),
    convertToPdf: z.boolean().optional()
});

export const zCreateSignatureDocumentControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string()
});

export const zCreateSignatureDocumentControllerRunResponse = z.object({
    url: z.string().optional()
});

export const zListSignatureGroupsControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string()
});

export const zListSignatureGroupsControllerRunQuery = z.object({
    filter: z.object({
        type: z.enum([
            'Document',
            'DocumentSignatory',
            'Signatory'
        ]).optional(),
        documentId: z.uuid().optional(),
        id: z.string().optional()
    }).optional(),
    order: z.object({
        createdAt: z.enum(['ASC', 'DESC']).optional()
    }).optional(),
    page: z.object({
        number: z.number().gte(1).default(1),
        size: z.number().gte(0).lte(100).default(20)
    }).optional()
});

export const zListSignatureGroupsControllerRunResponse = z.object({
    data: z.array(z.object({
        id: z.string(),
        requestId: z.string(),
        documentId: z.string().optional(),
        type: z.string(),
        index: z.number()
    })).optional(),
    meta: z.object({
        totalElements: z.number().optional()
    }).optional()
});

export const zCreateSignatureGroupControllerRunBody = z.object({
    id: z.string(),
    documentId: z.string().optional(),
    type: z.enum([
        'Document',
        'DocumentSignatory',
        'Signatory'
    ])
});

export const zCreateSignatureGroupControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string()
});

export const zListSignatureParticipantsControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string()
});

export const zListSignatureParticipantsControllerRunQuery = z.object({
    filter: z.object({
        role: z.enum([
            'SIGNATORY',
            'OBSERVER',
            'VALIDATOR'
        ]).optional(),
        groupIds: z.array(z.uuid()).optional(),
        id: z.string().optional()
    }).optional(),
    order: z.object({
        createdAt: z.enum(['ASC', 'DESC']).optional(),
        groupIndex: z.enum(['ASC', 'DESC']).optional(),
        email: z.enum(['ASC', 'DESC']).optional()
    }).optional(),
    page: z.object({
        number: z.number().gte(1).default(1),
        size: z.number().gte(0).lte(100).default(20)
    }).optional()
});

export const zListSignatureParticipantsControllerRunResponse = z.object({
    data: z.array(z.object({
        id: z.string(),
        requestId: z.string(),
        groupId: z.string().optional(),
        role: z.string(),
        firstName: z.string().optional(),
        lastName: z.string().optional(),
        email: z.string().optional(),
        createdAt: z.string(),
        phoneNumber: z.string().optional(),
        phonePrefix: z.string().optional(),
        participantStats: z.object({
            validators: z.number()
        }).optional(),
        editable: z.boolean(),
        emailBounced: z.boolean(),
        valid: z.boolean(),
        validationError: z.enum([
            'TAKEN',
            'IS_DEFINED',
            'IS_INVALID'
        ]).optional()
    })).optional(),
    meta: z.object({
        totalElements: z.number().optional()
    }).optional()
});

export const zCreateSignatureParticipantControllerRunBody = z.object({
    id: z.string(),
    groupId: z.string().optional(),
    role: z.enum([
        'SIGNATORY',
        'OBSERVER',
        'VALIDATOR'
    ]),
    firstName: z.string(),
    lastName: z.string(),
    email: z.string(),
    linkToAllDocuments: z.boolean().optional(),
    phoneNumber: z.string().optional(),
    phonePrefix: z.string().optional()
});

export const zCreateSignatureParticipantControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string()
});

export const zListSignatureRequestsByCaseFileControllerRunPath = z.object({
    caseFileId: z.string()
});

export const zListSignatureRequestsByCaseFileControllerRunQuery = z.object({
    filter: z.object({
        search: z.string().optional(),
        status: z.enum([
            'CREATING',
            'DRAFT',
            'ACTIVE',
            'PARTIALLY_SIGNED',
            'FULLY_SIGNED',
            'CANCELLED',
            'COMPLETED',
            'REJECTED',
            'CLOSING',
            'COMPLETED_MANUAL'
        ]).optional(),
        statuses: z.array(z.enum([
            'CREATING',
            'DRAFT',
            'ACTIVE',
            'PARTIALLY_SIGNED',
            'FULLY_SIGNED',
            'CANCELLED',
            'COMPLETED',
            'REJECTED',
            'CLOSING',
            'COMPLETED_MANUAL'
        ])).optional(),
        createdFrom: z.string().optional(),
        createdUntil: z.string().optional(),
        id: z.string().optional()
    }).optional(),
    order: z.object({
        createdAt: z.enum(['ASC', 'DESC']).optional()
    }).optional(),
    page: z.object({
        number: z.number().gte(1).default(1),
        size: z.number().gte(0).lte(100).default(20)
    }).optional()
});

export const zListSignatureRequestsByCaseFileControllerRunResponse = z.object({
    data: z.array(z.object({
        caseFileId: z.string(),
        id: z.string(),
        code: z.string(),
        name: z.string(),
        language: z.string(),
        status: z.enum([
            'CREATING',
            'DRAFT',
            'ACTIVE',
            'PARTIALLY_SIGNED',
            'FULLY_SIGNED',
            'CANCELLED',
            'COMPLETED',
            'REJECTED',
            'CLOSING',
            'COMPLETED_MANUAL'
        ]),
        createdAt: z.string(),
        activatedAt: z.string().optional(),
        completedAt: z.string().optional(),
        closeCondition: z.enum(['ALL_REQUIRED', 'PARTIAL_ALLOWED']),
        caseFile: z.object({
            id: z.string(),
            useCaseId: z.string(),
            name: z.string(),
            code: z.string()
        }),
        owner: z.object({
            id: z.string(),
            firstName: z.string(),
            lastName: z.string(),
            role: z.string()
        }),
        createdBy: z.object({
            id: z.string(),
            firstName: z.string(),
            lastName: z.string(),
            role: z.string()
        }).optional()
    })).optional(),
    meta: z.object({
        totalElements: z.number().optional()
    }).optional()
});

export const zCreateSignatureRequestControllerRunBody = z.object({
    id: z.uuid(),
    name: z.string().max(64),
    language: z.enum(['en_GB', 'es_ES']),
    signatureType: z.enum(['INTERPOSITION', 'ADVANCED']).optional(),
    dashboardUrl: z.enum(['NONE', 'ANONYMIZED']).optional(),
    sequence: z.enum(['PARALLEL', 'CONFIGURABLE']).optional(),
    deadline: z.string(),
    objectiveId: z.uuid().optional(),
    closeCondition: z.enum(['ALL_REQUIRED', 'PARTIAL_ALLOWED']).optional()
});

export const zCreateSignatureRequestControllerRunPath = z.object({
    caseFileId: z.string()
});

export const zDeleteDocumentParticipantControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string(),
    documentId: z.string(),
    id: z.string()
});

export const zDeleteInvalidSignatureParticipantsControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string()
});

export const zDeleteSignatoryValidatorControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string(),
    signatoryId: z.string(),
    validatorId: z.string()
});

export const zDeleteSignatureDocumentControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string(),
    documentId: z.string()
});

export const zUpdateSignatureDocumentControllerRunBody = z.object({
    groupId: z.string().optional()
});

export const zUpdateSignatureDocumentControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string(),
    documentId: z.string()
});

export const zDeleteSignatureGroupControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string(),
    groupId: z.string()
});

export const zDeleteSignatureParticipantControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string(),
    participantId: z.string()
});

export const zUpdateSignatureParticipantControllerRunBody = z.object({
    groupId: z.string().optional(),
    firstName: z.string().optional(),
    lastName: z.string().optional(),
    email: z.string().optional(),
    phonePrefix: z.string().optional(),
    phoneNumber: z.string().optional()
});

export const zUpdateSignatureParticipantControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string(),
    participantId: z.string()
});

export const zDeleteSignatureRequestControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string()
});

export const zShowSignatureRequestControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string()
});

export const zShowSignatureRequestControllerRunResponse = z.object({
    caseFileId: z.string(),
    id: z.string(),
    code: z.string(),
    name: z.string(),
    language: z.string(),
    status: z.enum([
        'CREATING',
        'DRAFT',
        'ACTIVE',
        'PARTIALLY_SIGNED',
        'FULLY_SIGNED',
        'CANCELLED',
        'COMPLETED',
        'REJECTED',
        'CLOSING',
        'COMPLETED_MANUAL'
    ]),
    createdAt: z.string(),
    signatureType: z.enum(['INTERPOSITION', 'ADVANCED']),
    dashboardUrl: z.enum(['NONE', 'ANONYMIZED']),
    sequence: z.enum(['PARALLEL', 'CONFIGURABLE']),
    activatedAt: z.string().optional(),
    completedAt: z.string().optional(),
    objectiveId: z.string().optional(),
    deadline: z.string(),
    closeCondition: z.enum(['ALL_REQUIRED', 'PARTIAL_ALLOWED']),
    signatoryStats: z.object({
        total: z.number(),
        bounced: z.number(),
        valid: z.number()
    }),
    observerStats: z.object({
        total: z.number(),
        bounced: z.number(),
        valid: z.number()
    }),
    validatorStats: z.object({
        total: z.number(),
        bounced: z.number(),
        assignedToSignatories: z.number(),
        assignedToDocuments: z.number(),
        valid: z.number()
    }),
    caseFile: z.object({
        id: z.string(),
        useCaseId: z.string(),
        name: z.string(),
        code: z.string(),
        ownerId: z.string()
    }),
    owner: z.object({
        id: z.string(),
        firstName: z.string(),
        lastName: z.string(),
        role: z.string()
    }),
    createdBy: z.object({
        id: z.string(),
        firstName: z.string(),
        lastName: z.string(),
        role: z.string()
    }).optional()
});

export const zUpdateSignatureRequestControllerRunBody = z.object({
    name: z.string().max(64).optional(),
    language: z.enum(['en_GB', 'es_ES']).optional(),
    deadline: z.string().optional(),
    dashboardUrl: z.enum(['NONE', 'ANONYMIZED']).optional(),
    objectiveId: z.uuid().optional()
});

export const zUpdateSignatureRequestControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string()
});

export const zDraftSignatureRequestControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string()
});

export const zDuplicateSignatureRequestControllerRunBody = z.object({
    caseFileId: z.uuid().optional(),
    id: z.uuid(),
    name: z.string().max(64),
    deadline: z.string()
});

export const zDuplicateSignatureRequestControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string()
});

export const zListSignatoryValidatorsFromDocumentControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string(),
    documentId: z.string(),
    signatoryId: z.string()
});

export const zListSignatoryValidatorsFromDocumentControllerRunQuery = z.object({
    page: z.object({
        number: z.number().gte(1).default(1),
        size: z.number().gte(0).lte(100).default(20)
    }).optional()
});

export const zListSignatoryValidatorsFromDocumentControllerRunResponse = z.object({
    data: z.array(z.object({
        id: z.string(),
        email: z.string(),
        firstName: z.string(),
        lastName: z.string(),
        status: z.enum([
            'PENDING',
            'READY_TO_VALIDATE',
            'VALIDATED',
            'REJECTED'
        ])
    })).optional(),
    meta: z.object({
        totalElements: z.number().optional()
    }).optional()
});

export const zLinkSignatoryValidatorsToDocumentControllerRunBody = z.object({
    validatorIds: z.array(z.uuid()).max(100)
});

export const zLinkSignatoryValidatorsToDocumentControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string(),
    documentId: z.string(),
    signatoryId: z.string()
});

export const zListDocumentObserversControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string(),
    documentId: z.string()
});

export const zListDocumentObserversControllerRunQuery = z.object({
    page: z.object({
        number: z.number().gte(1).default(1),
        size: z.number().gte(0).lte(100).default(20)
    }).optional()
});

export const zListDocumentObserversControllerRunResponse = z.object({
    data: z.array(z.object({
        id: z.string(),
        email: z.string(),
        firstName: z.string(),
        lastName: z.string()
    })).optional(),
    meta: z.object({
        totalElements: z.number().optional()
    }).optional()
});

export const zListDocumentSignatoriesControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string(),
    documentId: z.string()
});

export const zListDocumentSignatoriesControllerRunQuery = z.object({
    page: z.object({
        number: z.number().gte(1).default(1),
        size: z.number().gte(0).lte(100).default(20)
    }).optional()
});

export const zListDocumentSignatoriesControllerRunResponse = z.object({
    data: z.array(z.object({
        id: z.string(),
        groupId: z.string().optional(),
        email: z.string(),
        firstName: z.string(),
        lastName: z.string(),
        status: z.enum([
            'PENDING',
            'READY_TO_SIGN',
            'VALIDATING',
            'SIGNED',
            'REJECTED'
        ]),
        coordinates: z.array(z.object({
            page: z.number(),
            x: z.number(),
            y: z.number()
        })),
        uniqueValidator: z.boolean(),
        phoneNumber: z.string().optional(),
        phonePrefix: z.string().optional(),
        participantStats: z.object({
            validators: z.number()
        })
    })).optional(),
    meta: z.object({
        totalElements: z.number().optional()
    }).optional()
});

export const zListSignatoryValidatorsFromDocumentWithLinkedFlagControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string(),
    documentId: z.string(),
    signatoryId: z.string()
});

export const zListSignatoryValidatorsFromDocumentWithLinkedFlagControllerRunQuery = z.object({
    filter: z.object({
        search: z.string().optional()
    }).optional(),
    page: z.object({
        number: z.number().gte(1).default(1),
        size: z.number().gte(0).lte(100).default(20)
    }).optional()
});

export const zListSignatoryValidatorsFromDocumentWithLinkedFlagControllerRunResponse = z.object({
    data: z.array(z.object({
        id: z.string(),
        requestId: z.string(),
        documentId: z.string(),
        signatoryId: z.string(),
        firstName: z.string(),
        lastName: z.string(),
        email: z.string(),
        isLinked: z.boolean()
    })).optional(),
    meta: z.object({
        totalElements: z.number().optional()
    }).optional()
});

export const zListSignatoryValidatorsWithLinkedFlagControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string(),
    signatoryId: z.string()
});

export const zListSignatoryValidatorsWithLinkedFlagControllerRunQuery = z.object({
    filter: z.object({
        search: z.string().optional()
    }).optional(),
    page: z.object({
        number: z.number().gte(1).default(1),
        size: z.number().gte(0).lte(100).default(20)
    }).optional()
});

export const zListSignatoryValidatorsWithLinkedFlagControllerRunResponse = z.object({
    data: z.array(z.object({
        id: z.string(),
        requestId: z.string(),
        firstName: z.string(),
        lastName: z.string(),
        email: z.string(),
        isLinked: z.boolean()
    })).optional(),
    meta: z.object({
        totalElements: z.number().optional()
    }).optional()
});

export const zListSignatureParticipantsWithLinkedFlagControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string(),
    documentId: z.string()
});

export const zListSignatureParticipantsWithLinkedFlagControllerRunQuery = z.object({
    filter: z.object({
        role: z.enum([
            'SIGNATORY',
            'OBSERVER',
            'VALIDATOR'
        ]).optional(),
        search: z.string().optional()
    }).optional(),
    page: z.object({
        number: z.number().gte(1).default(1),
        size: z.number().gte(0).lte(100).default(20)
    }).optional()
});

export const zListSignatureParticipantsWithLinkedFlagControllerRunResponse = z.object({
    data: z.array(z.object({
        id: z.string(),
        requestId: z.string(),
        role: z.enum([
            'SIGNATORY',
            'OBSERVER',
            'VALIDATOR'
        ]),
        firstName: z.string(),
        lastName: z.string(),
        email: z.string(),
        createdAt: z.string(),
        isLinked: z.boolean()
    })).optional(),
    meta: z.object({
        totalElements: z.number().optional()
    }).optional()
});

export const zListSignatureRequestsByUserControllerRunPath = z.object({
    userId: z.string()
});

export const zListSignatureRequestsByUserControllerRunQuery = z.object({
    filter: z.object({
        search: z.string().optional(),
        status: z.enum([
            'CREATING',
            'DRAFT',
            'ACTIVE',
            'PARTIALLY_SIGNED',
            'FULLY_SIGNED',
            'CANCELLED',
            'COMPLETED',
            'REJECTED',
            'CLOSING',
            'COMPLETED_MANUAL'
        ]).optional(),
        statuses: z.array(z.enum([
            'CREATING',
            'DRAFT',
            'ACTIVE',
            'PARTIALLY_SIGNED',
            'FULLY_SIGNED',
            'CANCELLED',
            'COMPLETED',
            'REJECTED',
            'CLOSING',
            'COMPLETED_MANUAL'
        ])).optional(),
        createdFrom: z.string().optional(),
        createdUntil: z.string().optional(),
        id: z.string().optional(),
        caseFileIds: z.array(z.uuid()).optional()
    }).optional(),
    order: z.object({
        createdAt: z.enum(['ASC', 'DESC']).optional()
    }).optional(),
    page: z.object({
        number: z.number().gte(1).default(1),
        size: z.number().gte(0).lte(100).default(20)
    }).optional()
});

export const zListSignatureRequestsByUserControllerRunResponse = z.object({
    data: z.array(z.object({
        caseFileId: z.string(),
        id: z.string(),
        code: z.string(),
        name: z.string(),
        language: z.string(),
        status: z.enum([
            'CREATING',
            'DRAFT',
            'ACTIVE',
            'PARTIALLY_SIGNED',
            'FULLY_SIGNED',
            'CANCELLED',
            'COMPLETED',
            'REJECTED',
            'CLOSING',
            'COMPLETED_MANUAL'
        ]),
        createdAt: z.string(),
        activatedAt: z.string().optional(),
        completedAt: z.string().optional(),
        closeCondition: z.enum(['ALL_REQUIRED', 'PARTIAL_ALLOWED']),
        caseFile: z.object({
            id: z.string(),
            useCaseId: z.string(),
            name: z.string(),
            code: z.string()
        }),
        owner: z.object({
            id: z.string(),
            firstName: z.string(),
            lastName: z.string(),
            role: z.string()
        }),
        createdBy: z.object({
            id: z.string(),
            firstName: z.string(),
            lastName: z.string(),
            role: z.string()
        }).optional()
    })).optional(),
    meta: z.object({
        totalElements: z.number().optional()
    }).optional()
});

export const zProcessSignatureDocumentObserversCallbackControllerRunBody = z.object({
    operationType: z.string(),
    data: z.object({
        signatureRequestId: z.string(),
        email: z.string(),
        notification: z.object({
            status: z.enum(['BOUNCED'])
        })
    })
});

export const zProcessSignatureDocumentObserversCallbackControllerRunResponse = z.void();

export const zProcessSignatureDocumentSignatoriesCallbackControllerRunBody = z.object({
    operationType: z.string(),
    data: z.object({
        signatureRequestId: z.string(),
        email: z.string(),
        notification: z.object({
            status: z.enum(['BOUNCED'])
        })
    })
});

export const zProcessSignatureDocumentSignatoriesCallbackControllerRunResponse = z.void();

export const zProcessSignatureDocumentValidatorsCallbackControllerRunBody = z.object({
    operationType: z.string(),
    data: z.object({
        signatureRequestId: z.string(),
        email: z.string(),
        notification: z.object({
            status: z.enum(['BOUNCED'])
        })
    })
});

export const zProcessSignatureDocumentValidatorsCallbackControllerRunResponse = z.void();

export const zProcessSignatureDocumentsCallbackControllerRunBody = z.object({
    operationType: z.string(),
    data: z.object({
        signatureRequestId: z.string(),
        documentId: z.string(),
        status: z.string()
    })
});

export const zProcessSignatureDocumentsCallbackControllerRunResponse = z.void();

export const zProcessSignatureRequestsCallbackControllerRunBody = z.object({
    operationType: z.string(),
    data: z.object({
        signatureRequestId: z.string(),
        status: z.string()
    })
});

export const zProcessSignatureRequestsCallbackControllerRunResponse = z.void();

export const zResendSignatureRequestControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string()
});

export const zShowSignatureDocumentConvertedDownloadUrlControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string(),
    documentId: z.string()
});

export const zShowSignatureDocumentConvertedDownloadUrlControllerRunResponse = z.object({
    convertedDownloadUrl: z.string()
});

export const zShowSignatureDocumentDownloadUrlControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string(),
    documentId: z.string()
});

export const zShowSignatureDocumentDownloadUrlControllerRunResponse = z.object({
    downloadUrl: z.string()
});

export const zUnlinkSignatoryValidatorFromDocumentControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string(),
    documentId: z.string(),
    signatoryId: z.string(),
    validatorId: z.string()
});

export const zUpdateDocumentSignatoryControllerRunBody = z.object({
    groupId: z.string().optional(),
    uniqueValidator: z.boolean().optional()
});

export const zUpdateDocumentSignatoryControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string(),
    documentId: z.string(),
    signatoryId: z.string()
});

export const zUpdateSignatureCoordinatesControllerRunBody = z.object({
    coordinates: z.array(z.object({
        page: z.number(),
        x: z.number(),
        y: z.number()
    }))
});

export const zUpdateSignatureCoordinatesControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string(),
    documentId: z.string(),
    signatoryId: z.string()
});

export const zUpdateSignatureRequestCaseFileIdControllerRunBody = z.object({
    caseFileId: z.uuid()
});

export const zUpdateSignatureRequestCaseFileIdControllerRunPath = z.object({
    caseFileId: z.string(),
    requestId: z.string()
});

export const zListUseCasesControllerRunPath = z.object({
    companyId: z.string()
});

export const zListUseCasesControllerRunQuery = z.object({
    page: z.object({
        number: z.number().gte(1).default(1),
        size: z.number().gte(0).lte(100).default(20)
    }).optional()
});

export const zListUseCasesControllerRunResponse = z.object({
    data: z.array(z.object({
        id: z.string(),
        code: z.string(),
        index: z.number(),
        translations: z.array(z.object({
            id: z.string(),
            name: z.string(),
            language: z.string(),
            tipsDescription: z.string(),
            tipsList: z.array(z.string()),
            purposeDossier: z.string()
        }))
    })).optional(),
    meta: z.object({
        totalElements: z.number().optional()
    }).optional()
});

export const zListUseCasesControllerDeprecatedRunQuery = z.object({
    page: z.object({
        number: z.number().gte(1).default(1),
        size: z.number().gte(0).lte(100).default(20)
    }).optional()
});

export const zListUseCasesControllerDeprecatedRunResponse = z.object({
    data: z.array(z.object({
        id: z.string(),
        code: z.string(),
        index: z.number(),
        translations: z.array(z.object({
            id: z.string(),
            name: z.string(),
            language: z.string(),
            tipsDescription: z.string(),
            tipsList: z.array(z.string()),
            purposeDossier: z.string()
        }))
    })).optional(),
    meta: z.object({
        totalElements: z.number().optional()
    }).optional()
});
