// Auto-generated by the g-digital MCP distribution pipeline.
// Source MCP: @g-digital/mcp-ead-enterprise-suite (1.6.1)
// Architecture: REST-direct (Epic 12 ADR 0008). Token: fetched by the node for
// session/token auth; for the OAuth2 service-account style, n8n's oAuth2Api acquires it.

import {
  ICredentialType,
  INodeProperties,
} from 'n8n-workflow';

export class EadEnterpriseSuiteApi implements ICredentialType {
  name = 'eadEnterpriseSuiteApi';
  displayName = 'EAD Enterprise Suite API';

  icon = 'file:icon.svg' as const;
  documentationUrl = 'https://www.eadtrust.eu/soluciones-legaltech/enterprise-suite/';

  properties: INodeProperties[] = [
    {
      displayName: 'API Base URL',
      name: 'baseUrl',
      type: 'string',
      default: 'https://api-eadcustody.eadtrust.gocertius.io',
      description: 'Base URL of the EAD Enterprise Suite REST API. Leave as-is for the production environment (default: https://api-eadcustody.eadtrust.gocertius.io).',
    },
    {
      displayName: 'Auth Email',
      name: 'email',
      type: 'string',
      default: '',
      description: "Your EAD Enterprise Suite account email. Configure exactly one flow; do not combine it with the others.",
    },
    {
      displayName: 'Auth Password',
      name: 'password',
      type: 'string',
      typeOptions: { password: true },
      default: '',
      description: "Your EAD Enterprise Suite account password. (See https://www.eadtrust.eu/soluciones-legaltech/enterprise-suite/ for credential acquisition.)",
    },
    {
      displayName: 'User Key',
      name: 'userKey',
      type: 'string',
      typeOptions: { password: true },
      default: '',
      description: "Long-lived EAD Enterprise Suite user key, exchanged automatically for a short-lived session token. Use it for headless or automated access instead of an account password. Configure exactly one flow; do not combine it with the others. (See https://www.eadtrust.eu/soluciones-legaltech/enterprise-suite/ for credential acquisition.)",
    },
  ];

  // No *declarative* test here: the auth branches (User Key exchange vs
  // email/password login), which ICredentialTestRequest cannot express. The node
  // supplies a programmatic one instead — see the `testAuth` credentialTest method
  // in the node class, wired up through `testedBy`. The credential still gets its
  // green check on Save, for both flows.
}
