// Auto-generated by the g-digital MCP distribution pipeline.
// Source MCP: @g-digital/mcp-ead-enterprise-suite (2.0.0)
// Architecture: REST-direct (Epic 12 ADR 0008). Token: fetched by the node for
// session/token auth; for the OAuth2 service-account style, n8n's oAuth2Api acquires it.

import {
  ICredentialType,
  INodeProperties,
} from 'n8n-workflow';

export class EadEnterpriseSuiteApi implements ICredentialType {
  name = 'eadEnterpriseSuiteApi';
  displayName = 'EAD Enterprise Suite API';

  icon = 'file:icon.svg' as const;
  documentationUrl = 'https://www.eadtrust.eu/soluciones-legaltech/enterprise-suite/';

  properties: INodeProperties[] = [
    {
      displayName: 'API Base URL',
      name: 'baseUrl',
      type: 'string',
      required: true,
      default: 'https://api-eadcustody.eadtrust.gocertius.io',
      description: "Upstream API root. Required: your user key is exchanged for a session token against this host, and the server will not start without it.",
    },
    {
      displayName: 'User Key',
      name: 'userKey',
      type: 'string',
      typeOptions: { password: true },
      required: true,
      default: '',
      description: "Long-lived EAD Enterprise Suite user key, exchanged automatically for a short-lived session token. Use it for headless or automated access instead of an account password. (See https://www.eadtrust.eu/soluciones-legaltech/enterprise-suite/ for credential acquisition.)",
    },
  ];

  // No *declarative* test here: the User Key exchange posts the key in the request
  // BODY and reads the session token out of the response, which
  // ICredentialTestRequest cannot express. The node supplies a programmatic one
  // instead — see the `testAuth` credentialTest method in the node class, wired up
  // through `testedBy`. The credential still gets its green check on Save.
}
