// Auto-generated by the g-digital MCP distribution pipeline.
// Source MCP: @g-digital/mcp-ead-enterprise-suite (1.3.10)
// Architecture: REST-direct (Epic 12 ADR 0008) — Bearer token fetched by the node.

import {
  ICredentialTestRequest,
  ICredentialType,
  INodeProperties,
} from 'n8n-workflow';

export class EadEnterpriseSuiteApi implements ICredentialType {
  name = 'eadEnterpriseSuiteApi';
  displayName = 'Ead Enterprise Suite API';
  documentationUrl = 'https://www.eadtrust.eu/soluciones-legaltech/enterprise-suite/';

  properties: INodeProperties[] = [
    {
      displayName: 'API Base URL',
      name: 'baseUrl',
      type: 'string',
      default: 'https://api-eadcustody.eadtrust.gocertius.io',
      description: 'Base URL of the Ead Enterprise Suite REST API. Leave as-is for the production environment (default: https://api-eadcustody.eadtrust.gocertius.io).',
    },
    {
      displayName: 'Account Email',
      name: 'email',
      type: 'string',
      default: '',
      description: "The email address associated with your EAD Enterprise Suite account.",
    },
    {
      displayName: 'Account Password',
      name: 'password',
      type: 'string',
      typeOptions: { password: true },
      default: '',
      description: "The password for your EAD Enterprise Suite account, obtainable at eadtrust.eu.",
    },
  ];

  test: ICredentialTestRequest = {
    request: {
      baseURL: '={{$credentials.baseUrl}}',
      url: '/session',
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: {
        email: '={{$credentials.email}}',
        password: '={{$credentials.password}}',
      },
    },
  };
}
