// Auto-generated by @suite/generator. Do not edit.
// MCP server entry point for EAD Enterprise Suite

import { createServer } from "./core/server.js";
import { evidence_create } from "./tools/evidence_create.js";
import { evidence_list } from "./tools/evidence_list.js";
import { evidence_seal } from "./tools/evidence_seal.js";
import { evidence_get } from "./tools/evidence_get.js";
import { evidence_group_create } from "./tools/evidence_group_create.js";
import { evidence_group_list } from "./tools/evidence_group_list.js";
import { dossier_create } from "./tools/dossier_create.js";
import { dossier_list } from "./tools/dossier_list.js";
import { dossier_get } from "./tools/dossier_get.js";
import { dossier_template_list } from "./tools/dossier_template_list.js";
import { notification_request_create } from "./tools/notification_request_create.js";
import { notification_request_send } from "./tools/notification_request_send.js";
import { notification_request_status } from "./tools/notification_request_status.js";
import { notification_receiver_add } from "./tools/notification_receiver_add.js";
import { notification_certificate_get } from "./tools/notification_certificate_get.js";
import { case_file_list } from "./tools/case_file_list.js";
import { case_file_get } from "./tools/case_file_get.js";
import { session_login } from "./tools/session_login.js";
import { session_info } from "./tools/session_info.js";
import { use_case_list } from "./tools/use_case_list.js";
import { signature_request_create } from "./tools/signature_request_create.js";
import { signature_request_get } from "./tools/signature_request_get.js";
import { signature_request_cancel } from "./tools/signature_request_cancel.js";
import { signature_request_add_document } from "./tools/signature_request_add_document.js";
import { signature_document_list } from "./tools/signature_document_list.js";
import { signature_participant_create } from "./tools/signature_participant_create.js";
import { signature_participant_list } from "./tools/signature_participant_list.js";
import { signature_coordinate_set } from "./tools/signature_coordinate_set.js";
import { activate_signature_request } from "./tools/activate_signature_request.js";
import { signature_certificate_get } from "./tools/signature_certificate_get.js";
import { signature_request_full_create } from "./tools/signature_request_full_create.js";
import { large_evidence_upload_initiate } from "./tools/large_evidence_upload_initiate.js";
import { large_evidence_upload_complete } from "./tools/large_evidence_upload_complete.js";

await createServer({
  name: "io.github.g-digital-by-Garrigues/ead-enterprise-suite",
  version: "1.0.0",
  tools: [
    evidence_create,
evidence_list,
evidence_seal,
evidence_get,
evidence_group_create,
evidence_group_list,
dossier_create,
dossier_list,
dossier_get,
dossier_template_list,
notification_request_create,
notification_request_send,
notification_request_status,
notification_receiver_add,
notification_certificate_get,
case_file_list,
case_file_get,
session_login,
session_info,
use_case_list,
signature_request_create,
signature_request_get,
signature_request_cancel,
signature_request_add_document,
signature_document_list,
signature_participant_create,
signature_participant_list,
signature_coordinate_set,
activate_signature_request,
signature_certificate_get,
signature_request_full_create,
large_evidence_upload_initiate,
large_evidence_upload_complete,
  ],
});
