// Auto-generated by @suite/generator. Do not edit.
// Sourced from operation: CreateSignatoryValidatorsController_run (POST /case-files/{caseFileId}/signature-requests/{requestId}/signatories/{signatoryId}/validators)

import { defineTool } from "../core/index.js";
import { z } from "zod";
import { createClient, createConfig } from "../api/client/index.js";
import { createSignatoryValidatorsControllerRun } from "../api/sdk.gen.js";
import { zCreateSignatoryValidatorsControllerRunPath } from "../api/zod.gen.js";
import { zCreateSignatoryValidatorsControllerRunBody } from "../api/zod.gen.js";
const inputSchema = z.object({
  ...zCreateSignatoryValidatorsControllerRunPath.shape,
  ...zCreateSignatoryValidatorsControllerRunBody.shape,
});

export const assign_validator_to_signatory = defineTool({
  name: "assign_validator_to_signatory",
  description: "Assigns one or more validators to a specific signatory in a signature request. The validator must approve before the signatory can sign. Requires: signature_participant_create (validator) → validatorId in validatorIds array, signature_participant_create (signatory) → signatoryId, signature_request_create → requestId, case_file_create → caseFileId.",
  inputSchema,
  annotations: {
    title: "Assign Validator To Signatory",
    readOnlyHint: false,
    destructiveHint: false,
    idempotentHint: false,
    openWorldHint: false,
  },
  pollable: false,
  idempotencyWindowSeconds: 60,
  async execute(input, ctx) {
    const token = ctx.auth?.token ?? "";
    const sdkClient = createClient(
      createConfig({
        baseUrl: process.env.MCP_API_BASE_URL ?? "https://api-eadcustody.eadtrust.gocertius.io",
        headers: {
          Authorization: `Bearer ${token}`,
          ...(ctx.correlationId ? { "X-Correlation-Id": ctx.correlationId } : {}),
        },
      }),
    );

    // biome-ignore lint/suspicious/noExplicitAny: generated SDK call — input shape validated above
    const inp = input as any;
    // biome-ignore lint/suspicious/noExplicitAny: generated SDK function — types validated at generation time
    const sdkFn = createSignatoryValidatorsControllerRun as (opts: any) => Promise<any>;
    const response = await sdkFn({
      client: sdkClient,
      path: zCreateSignatoryValidatorsControllerRunPath.parse(inp),
      body: zCreateSignatoryValidatorsControllerRunBody.parse(inp),
    });

    if (response.error !== undefined) {
      const msg = typeof response.error === "object" && response.error !== null && "message" in response.error
        ? String(response.error.message)
        : JSON.stringify(response.error);
      throw new Error(msg);
    }
    return response.data;
  },
});
