// Auto-generated by @suite/generator. Do not edit.
// Sourced from operation: LinkDossierEvidencesController_run (POST /case-files/{caseFileId}/dossiers/{dossierId}/case-files-to-link/{caseFileToLinkId}/link-evidences)

import { defineTool, UpstreamHttpError } from "../core/index.js";
import { z } from "zod";
import { createClient, createConfig } from "../api/client/index.js";
import { linkDossierEvidencesControllerRun } from "../api/sdk.gen.js";
import { zLinkDossierEvidencesControllerRunPath } from "../api/zod.gen.js";
import { zLinkDossierEvidencesControllerRunBody } from "../api/zod.gen.js";
const rawInputSchema = z.object({
  ...zLinkDossierEvidencesControllerRunPath.shape,
  ...zLinkDossierEvidencesControllerRunBody.shape,
});
// Story 6.5 (FR-27/P-A5): fills in descriptions for commonly reused field names
// (e.g. caseFileId) that Hey API's generated schema doesn't carry on its own.
const inputSchema = rawInputSchema;

export const dossier_evidence_link = defineTool({
  name: "dossier_evidence_link",
  description: "Links evidence items from a sealed group to a dossier. Requires: dossier_create → dossierId, evidence_seal (CLOSED), case_file_create → caseFileId. Pass the ids array of evidence UUIDs. Can be called multiple times for evidence from different case files.",
  inputSchema,
  annotations: {
    title: "Dossier Evidence Link",
    readOnlyHint: false,
    destructiveHint: false,
    idempotentHint: false,
    openWorldHint: false,
  },
  pollable: false,
  idempotencyWindowSeconds: 60,
  async execute(input, ctx) {
    const token = ctx.auth?.token ?? "";
    const sdkClient = createClient(
      createConfig({
        baseUrl: process.env.MCP_API_BASE_URL ?? "https://api-eadcustody.eadtrust.gocertius.io",
        headers: {
          Authorization: `Bearer ${token}`,
          ...(ctx.correlationId ? { "X-Correlation-Id": ctx.correlationId } : {}),
        },
      }),
    );

    // biome-ignore lint/suspicious/noExplicitAny: generated SDK call — input shape validated above
    const inp = input as any;
    // biome-ignore lint/suspicious/noExplicitAny: generated SDK function — types validated at generation time
    const sdkFn = linkDossierEvidencesControllerRun as (opts: any) => Promise<any>;
    const response = await sdkFn({
      client: sdkClient,
      path: zLinkDossierEvidencesControllerRunPath.parse(inp),
      body: zLinkDossierEvidencesControllerRunBody.parse(inp),
    });

    if (response.error !== undefined) {
      // Story 10.2: constructs a status-aware UpstreamHttpError instead of a plain
      // Error — mapUpstreamError's 422 field-hint / 5xx transient-retry branches can
      // only be reached this way; a plain Error always fell through to the generic
      // "transient failure" text, discarding the real HTTP status/detail. Uses
      // fromParsedError (not fromResponse) because @hey-api/client-fetch has already
      // consumed response.response's body to populate response.error by this point.
      throw UpstreamHttpError.fromParsedError(response.response?.status ?? 0, response.error, "dossier_evidence_link");
    }
    return response.data;
  },
});
