// Auto-generated by @suite/generator. Do not edit.
// Sourced from operation: CreateLargeEvidenceUploadController_run (POST /case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/large-evidence-uploads)

import { defineTool } from "../core/index.js";
import { z } from "zod";
import { createClient, createConfig } from "../api/client/index.js";
import { createLargeEvidenceUploadControllerRun } from "../api/sdk.gen.js";
import { zCreateLargeEvidenceUploadControllerRunPath } from "../api/zod.gen.js";
import { zCreateLargeEvidenceUploadControllerRunBody } from "../api/zod.gen.js";
const inputSchema = z.object({
  ...zCreateLargeEvidenceUploadControllerRunPath.shape,
  ...zCreateLargeEvidenceUploadControllerRunBody.shape,
});

export const large_evidence_upload_initiate = defineTool({
  name: "large_evidence_upload_initiate",
  description: "Performs the large_evidence_upload_initiate operation against the GoCertius API. Review the API documentation for full field details.",
  inputSchema,
  annotations: {
    destructive: false,
    idempotent: false,
    requiresUserConfirmation: false,
  },
  pollable: true,
  idempotencyWindowSeconds: 86400,
  async execute(input, ctx) {
    const token = ctx.auth?.token ?? "";
    const sdkClient = createClient(
      createConfig({
        baseUrl: process.env.MCP_API_BASE_URL ?? "",
        headers: { Authorization: `Bearer ${token}` },
      }),
    );

    // biome-ignore lint/suspicious/noExplicitAny: generated SDK call — input shape validated above
    const inp = input as any;
    // biome-ignore lint/suspicious/noExplicitAny: generated SDK function — types validated at generation time
    const sdkFn = createLargeEvidenceUploadControllerRun as (opts: any) => Promise<any>;
    const response = await sdkFn({
      client: sdkClient,
      path: zCreateLargeEvidenceUploadControllerRunPath.parse(inp),
      body: zCreateLargeEvidenceUploadControllerRunBody.parse(inp),
    });

    if (response.error !== undefined) {
      const msg = typeof response.error === "object" && response.error !== null && "message" in response.error
        ? String(response.error.message)
        : JSON.stringify(response.error);
      throw new Error(msg);
    }
    return response.data;
  },
});
