// Auto-generated by @suite/generator. Do not edit.
// Sourced from operation: CreateEvidenceGroupCloseRequestController_run (POST /case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/close-request)

import { defineTool } from "../core/index.js";
import { z } from "zod";
import { createClient, createConfig } from "../api/client/index.js";
import { createEvidenceGroupCloseRequestControllerRun } from "../api/sdk.gen.js";
import { zCreateEvidenceGroupCloseRequestControllerRunPath } from "../api/zod.gen.js";
import { zCreateEvidenceGroupCloseRequestControllerRunBody } from "../api/zod.gen.js";
const inputSchema = z.object({
  ...zCreateEvidenceGroupCloseRequestControllerRunPath.shape,
  ...zCreateEvidenceGroupCloseRequestControllerRunBody.shape,
});

export const large_evidence_upload_complete = defineTool({
  name: "large_evidence_upload_complete",
  description: "Performs the large_evidence_upload_complete operation against the GoCertius API. Review the API documentation for full field details.",
  inputSchema,
  annotations: {
    destructive: false,
    idempotent: false,
    requiresUserConfirmation: false,
  },
  pollable: true,
  idempotencyWindowSeconds: 86400,
  async execute(input, ctx) {
    const token = ctx.auth?.token ?? "";
    const sdkClient = createClient(
      createConfig({
        baseUrl: process.env.MCP_API_BASE_URL ?? "",
        headers: { Authorization: `Bearer ${token}` },
      }),
    );

    // biome-ignore lint/suspicious/noExplicitAny: generated SDK call — input shape validated above
    const inp = input as any;
    // biome-ignore lint/suspicious/noExplicitAny: generated SDK function — types validated at generation time
    const sdkFn = createEvidenceGroupCloseRequestControllerRun as (opts: any) => Promise<any>;
    const response = await sdkFn({
      client: sdkClient,
      path: zCreateEvidenceGroupCloseRequestControllerRunPath.parse(inp),
      body: zCreateEvidenceGroupCloseRequestControllerRunBody.parse(inp),
    });

    if (response.error !== undefined) {
      const msg = typeof response.error === "object" && response.error !== null && "message" in response.error
        ? String(response.error.message)
        : JSON.stringify(response.error);
      throw new Error(msg);
    }
    return response.data;
  },
});
