// Auto-generated by @suite/generator. Do not edit.
// Sourced from operation: CreateSignatureDocumentController_run (POST /case-files/{caseFileId}/signature-requests/{requestId}/documents)

import { defineTool } from "../core/index.js";
import { z } from "zod";
import { createClient, createConfig } from "../api/client/index.js";
import { createSignatureDocumentControllerRun } from "../api/sdk.gen.js";
import { zCreateSignatureDocumentControllerRunPath } from "../api/zod.gen.js";
import { zCreateSignatureDocumentControllerRunBody } from "../api/zod.gen.js";
const inputSchema = z.object({
  ...zCreateSignatureDocumentControllerRunPath.shape,
  ...zCreateSignatureDocumentControllerRunBody.shape,
});

export const signature_request_add_document = defineTool({
  name: "signature_request_add_document",
  description: "Adds a document to a DRAFT signature request. Requires: signature_request_create → requestId, case_file_create → caseFileId. Provide a string `id` for the document. Compute SHA-256 hex hash of the PDF before calling. Returns documentId and url (presigned S3 upload URL) — PUT the PDF bytes to url before adding participants. Cannot add documents after activate_signature_request is called.",
  inputSchema,
  annotations: {
    destructive: false,
    idempotent: false,
    requiresUserConfirmation: false,
  },
  pollable: false,
  idempotencyWindowSeconds: 60,
  async execute(input, ctx) {
    const token = ctx.auth?.token ?? "";
    const sdkClient = createClient(
      createConfig({
        baseUrl: process.env.MCP_API_BASE_URL ?? "",
        headers: {
          Authorization: `Bearer ${token}`,
          ...(ctx.correlationId ? { "X-Correlation-Id": ctx.correlationId } : {}),
        },
      }),
    );

    // biome-ignore lint/suspicious/noExplicitAny: generated SDK call — input shape validated above
    const inp = input as any;
    // biome-ignore lint/suspicious/noExplicitAny: generated SDK function — types validated at generation time
    const sdkFn = createSignatureDocumentControllerRun as (opts: any) => Promise<any>;
    const response = await sdkFn({
      client: sdkClient,
      path: zCreateSignatureDocumentControllerRunPath.parse(inp),
      body: zCreateSignatureDocumentControllerRunBody.parse(inp),
    });

    if (response.error !== undefined) {
      const msg = typeof response.error === "object" && response.error !== null && "message" in response.error
        ? String(response.error.message)
        : JSON.stringify(response.error);
      throw new Error(msg);
    }
    return response.data;
  },
});
