// Auto-generated by @suite/generator. Do not edit.
// Sourced from operation: CreateSignatureParticipantController_run (POST /case-files/{caseFileId}/signature-requests/{requestId}/participants)

import { defineTool } from "../core/index.js";
import { z } from "zod";
import { createClient, createConfig } from "../api/client/index.js";
import { createSignatureParticipantControllerRun } from "../api/sdk.gen.js";
import { zCreateSignatureParticipantControllerRunPath } from "../api/zod.gen.js";
import { zCreateSignatureParticipantControllerRunBody } from "../api/zod.gen.js";
const inputSchema = z.object({
  ...zCreateSignatureParticipantControllerRunPath.shape,
  ...zCreateSignatureParticipantControllerRunBody.shape,
});

export const signature_participant_create = defineTool({
  name: "signature_participant_create",
  description:
    "Add a signatory, observer, or validator to a signature request. " +
    "phonePrefix must include the '+' sign (e.g. '+34'). " +
    "For INTERPOSITION signature types, call signature_coordinate_set after this to define the signature box position. " +
    "Use signature_request_full_create to handle participants and coordinates in a single call.",
  inputSchema,
  annotations: {
    destructive: false,
    idempotent: false,
    requiresUserConfirmation: false,
  },
  pollable: false,
  idempotencyWindowSeconds: 60,
  async execute(input, ctx) {
    const token = ctx.auth?.token ?? "";
    const sdkClient = createClient(
      createConfig({
        baseUrl: process.env.MCP_API_BASE_URL ?? "",
        headers: {
          Authorization: `Bearer ${token}`,
          ...(ctx.correlationId ? { "X-Correlation-Id": ctx.correlationId } : {}),
        },
      }),
    );

    // biome-ignore lint/suspicious/noExplicitAny: generated SDK call — input shape validated above
    const inp = input as any;
    // biome-ignore lint/suspicious/noExplicitAny: generated SDK function — types validated at generation time
    const sdkFn = createSignatureParticipantControllerRun as (opts: any) => Promise<any>;
    const response = await sdkFn({
      client: sdkClient,
      path: zCreateSignatureParticipantControllerRunPath.parse(inp),
      body: zCreateSignatureParticipantControllerRunBody.parse(inp),
    });

    if (response.error !== undefined) {
      const msg = typeof response.error === "object" && response.error !== null && "message" in response.error
        ? String(response.error.message)
        : JSON.stringify(response.error);
      throw new Error(msg);
    }
    return response.data;
  },
});
