// Auto-generated by @suite/generator. Do not edit.
// Sourced from operation: ShowSignatureCertificateDocumentUrlController_run (GET /case-files/{caseFileId}/signature-requests/{requestId}/documents/{documentId}/certificates/document-url)

import { defineTool } from "../core/index.js";
import { z } from "zod";
import { createClient, createConfig } from "../api/client/index.js";
import { showSignatureCertificateDocumentUrlControllerRun } from "../api/sdk.gen.js";
import { zShowSignatureCertificateDocumentUrlControllerRunPath } from "../api/zod.gen.js";
const inputSchema = z.object({
  ...zShowSignatureCertificateDocumentUrlControllerRunPath.shape,
});

export const signature_certificate_get = defineTool({
  name: "signature_certificate_get",
  description: "Retrieves the signed document certificate PDF. Requires: activate_signature_request (document fully SIGNED), signature_request_add_document → documentId, signature_request_create → requestId, case_file_create → caseFileId. Returns documentUrl (signed PDF certificate). ASYNC: poll until documentUrl is available.",
  inputSchema,
  annotations: {
    destructive: false,
    idempotent: true,
    requiresUserConfirmation: false,
  },
  pollable: false,
  idempotencyWindowSeconds: 60,
  async execute(input, ctx) {
    const token = ctx.auth?.token ?? "";
    const sdkClient = createClient(
      createConfig({
        baseUrl: process.env.MCP_API_BASE_URL ?? "",
        headers: {
          Authorization: `Bearer ${token}`,
          ...(ctx.correlationId ? { "X-Correlation-Id": ctx.correlationId } : {}),
        },
      }),
    );

    // biome-ignore lint/suspicious/noExplicitAny: generated SDK call — input shape validated above
    const inp = input as any;
    // biome-ignore lint/suspicious/noExplicitAny: generated SDK function — types validated at generation time
    const sdkFn = showSignatureCertificateDocumentUrlControllerRun as (opts: any) => Promise<any>;
    const response = await sdkFn({
      client: sdkClient,
      path: zShowSignatureCertificateDocumentUrlControllerRunPath.parse(inp),
    });

    if (response.error !== undefined) {
      const msg = typeof response.error === "object" && response.error !== null && "message" in response.error
        ? String(response.error.message)
        : JSON.stringify(response.error);
      throw new Error(msg);
    }
    return response.data;
  },
});
