// Auto-generated by @suite/generator. Do not edit.
// Sourced from operation: CreateSignatureRequestController_run (POST /case-files/{caseFileId}/signature-requests)

import { defineTool } from "../core/index.js";
import { z } from "zod";
import { createClient, createConfig } from "../api/client/index.js";
import { createSignatureRequestControllerRun } from "../api/sdk.gen.js";
import { zCreateSignatureRequestControllerRunPath } from "../api/zod.gen.js";
import { zCreateSignatureRequestControllerRunBody } from "../api/zod.gen.js";
const inputSchema = z.object({
  ...zCreateSignatureRequestControllerRunPath.shape,
  ...zCreateSignatureRequestControllerRunBody.shape,
});

export const signature_request_create = defineTool({
  name: "signature_request_create",
  description: "Creates a new signature request in DRAFT status. Requires: case_file_create → caseFileId. Generate a UUID v4 for `id`. Set deadline as ISO 8601 datetime (max ~30 days ahead). Returns requestId. Add documents with signature_request_add_document and participants with signature_participant_create before activating.",
  inputSchema,
  annotations: {
    title: "Signature Request Create",
    readOnlyHint: false,
    destructiveHint: false,
    idempotentHint: false,
    openWorldHint: false,
  },
  pollable: false,
  idempotencyWindowSeconds: 60,
  async execute(input, ctx) {
    const token = ctx.auth?.token ?? "";
    const sdkClient = createClient(
      createConfig({
        baseUrl: process.env.MCP_API_BASE_URL ?? "https://api-eadcustody.eadtrust.gocertius.io",
        headers: {
          Authorization: `Bearer ${token}`,
          ...(ctx.correlationId ? { "X-Correlation-Id": ctx.correlationId } : {}),
        },
      }),
    );

    // biome-ignore lint/suspicious/noExplicitAny: generated SDK call — input shape validated above
    const inp = input as any;
    // biome-ignore lint/suspicious/noExplicitAny: generated SDK function — types validated at generation time
    const sdkFn = createSignatureRequestControllerRun as (opts: any) => Promise<any>;
    const response = await sdkFn({
      client: sdkClient,
      path: zCreateSignatureRequestControllerRunPath.parse(inp),
      body: zCreateSignatureRequestControllerRunBody.parse(inp),
    });

    if (response.error !== undefined) {
      const msg = typeof response.error === "object" && response.error !== null && "message" in response.error
        ? String(response.error.message)
        : JSON.stringify(response.error);
      throw new Error(msg);
    }
    return response.data;
  },
});
