// Auto-generated by @suite/generator. Do not edit.
// Sourced from operation: ListSignatureGroupsController_run (GET /case-files/{caseFileId}/signature-requests/{requestId}/groups)

import { defineTool } from "../core/index.js";
import { z } from "zod";
import { createClient, createConfig } from "../api/client/index.js";
import { listSignatureGroupsControllerRun } from "../api/sdk.gen.js";
import { zListSignatureGroupsControllerRunPath } from "../api/zod.gen.js";
import { zListSignatureGroupsControllerRunQuery } from "../api/zod.gen.js";
const inputSchema = z.object({
  ...zListSignatureGroupsControllerRunPath.shape,
  ...zListSignatureGroupsControllerRunQuery.shape,
});

export const signature_group_list = defineTool({
  name: "signature_group_list",
  description: "Lists all signing order groups of a CONFIGURABLE signature request. Returns id, type (Document/Signatory/DocumentSignatory), index, and documentId for each group. Call immediately after signature_request_create to retrieve the pre-created index:1 group IDs before adding documents or participants.",
  inputSchema,
  annotations: {
    title: "Signature Group List",
    readOnlyHint: true,
    destructiveHint: false,
    idempotentHint: true,
    openWorldHint: false,
  },
  pollable: false,
  idempotencyWindowSeconds: 60,
  async execute(input, ctx) {
    const token = ctx.auth?.token ?? "";
    const sdkClient = createClient(
      createConfig({
        baseUrl: process.env.MCP_API_BASE_URL ?? "https://api-eadcustody.eadtrust.gocertius.io",
        headers: {
          Authorization: `Bearer ${token}`,
          ...(ctx.correlationId ? { "X-Correlation-Id": ctx.correlationId } : {}),
        },
      }),
    );

    // biome-ignore lint/suspicious/noExplicitAny: generated SDK call — input shape validated above
    const inp = input as any;
    // biome-ignore lint/suspicious/noExplicitAny: generated SDK function — types validated at generation time
    const sdkFn = listSignatureGroupsControllerRun as (opts: any) => Promise<any>;
    const response = await sdkFn({
      client: sdkClient,
      path: zListSignatureGroupsControllerRunPath.parse(inp),
      query: zListSignatureGroupsControllerRunQuery.parse(inp),
    });

    if (response.error !== undefined) {
      const msg = typeof response.error === "object" && response.error !== null && "message" in response.error
        ? String(response.error.message)
        : JSON.stringify(response.error);
      throw new Error(msg);
    }
    return response.data;
  },
});
