// Auto-generated by @suite/generator. Do not edit.
// Sourced from operation: UpdateSignatureCoordinatesController_run (PUT /case-files/{caseFileId}/signature-requests/{requestId}/documents/{documentId}/signatories/{signatoryId}/coordinates)

import { defineTool } from "../core/index.js";
import { z } from "zod";
import { createClient, createConfig } from "../api/client/index.js";
import { updateSignatureCoordinatesControllerRun } from "../api/sdk.gen.js";
import { zUpdateSignatureCoordinatesControllerRunPath } from "../api/zod.gen.js";
import { zUpdateSignatureCoordinatesControllerRunBody } from "../api/zod.gen.js";
const inputSchema = z.object({
  ...zUpdateSignatureCoordinatesControllerRunPath.shape,
  ...zUpdateSignatureCoordinatesControllerRunBody.shape,
});

export const signature_coordinate_set = defineTool({
  name: "signature_coordinate_set",
  description: "Sets the visual position of the signature field on a document page. Requires: signature_participant_create → signatoryId, signature_request_add_document → documentId, signature_request_create → requestId, case_file_create → caseFileId. Provide coordinates as array of {page (1-based), x (points from left), y (points from bottom)}. Required for all signature types (INTERPOSITION and ADVANCED) before activation.",
  inputSchema,
  annotations: {
    destructive: false,
    idempotent: false,
    requiresUserConfirmation: false,
  },
  pollable: false,
  idempotencyWindowSeconds: 60,
  async execute(input, ctx) {
    const token = ctx.auth?.token ?? "";
    const sdkClient = createClient(
      createConfig({
        baseUrl: process.env.MCP_API_BASE_URL ?? "",
        headers: {
          Authorization: `Bearer ${token}`,
          ...(ctx.correlationId ? { "X-Correlation-Id": ctx.correlationId } : {}),
        },
      }),
    );

    // biome-ignore lint/suspicious/noExplicitAny: generated SDK call — input shape validated above
    const inp = input as any;
    // biome-ignore lint/suspicious/noExplicitAny: generated SDK function — types validated at generation time
    const sdkFn = updateSignatureCoordinatesControllerRun as (opts: any) => Promise<any>;
    const response = await sdkFn({
      client: sdkClient,
      path: zUpdateSignatureCoordinatesControllerRunPath.parse(inp),
      body: zUpdateSignatureCoordinatesControllerRunBody.parse(inp),
    });

    if (response.error !== undefined) {
      const msg = typeof response.error === "object" && response.error !== null && "message" in response.error
        ? String(response.error.message)
        : JSON.stringify(response.error);
      throw new Error(msg);
    }
    return response.data;
  },
});
