// Auto-generated by @suite/generator. Do not edit.
// Sourced from operation: ListDocumentObserversController_run (GET /case-files/{caseFileId}/signature-requests/{requestId}/documents/{documentId}/observers)

import { defineTool } from "../core/index.js";
import { z } from "zod";
import { createClient, createConfig } from "../api/client/index.js";
import { listDocumentObserversControllerRun } from "../api/sdk.gen.js";
import { zListDocumentObserversControllerRunPath } from "../api/zod.gen.js";
import { zListDocumentObserversControllerRunQuery } from "../api/zod.gen.js";
const inputSchema = z.object({
  ...zListDocumentObserversControllerRunPath.shape,
  ...zListDocumentObserversControllerRunQuery.shape,
});

export const signature_participant_list = defineTool({
  name: "signature_participant_list",
  description: "Lists all participants of a signature request. Requires: signature_request_create → requestId, case_file_create → caseFileId. Returns roles, contact details, and signing status.",
  inputSchema,
  annotations: {
    destructive: false,
    idempotent: true,
    requiresUserConfirmation: false,
  },
  pollable: false,
  idempotencyWindowSeconds: 60,
  async execute(input, ctx) {
    const token = ctx.auth?.token ?? "";
    const sdkClient = createClient(
      createConfig({
        baseUrl: process.env.MCP_API_BASE_URL ?? "",
        headers: {
          Authorization: `Bearer ${token}`,
          ...(ctx.correlationId ? { "X-Correlation-Id": ctx.correlationId } : {}),
        },
      }),
    );

    // biome-ignore lint/suspicious/noExplicitAny: generated SDK call — input shape validated above
    const inp = input as any;
    // biome-ignore lint/suspicious/noExplicitAny: generated SDK function — types validated at generation time
    const sdkFn = listDocumentObserversControllerRun as (opts: any) => Promise<any>;
    const response = await sdkFn({
      client: sdkClient,
      path: zListDocumentObserversControllerRunPath.parse(inp),
      query: zListDocumentObserversControllerRunQuery.parse(inp),
    });

    if (response.error !== undefined) {
      const msg = typeof response.error === "object" && response.error !== null && "message" in response.error
        ? String(response.error.message)
        : JSON.stringify(response.error);
      throw new Error(msg);
    }
    return response.data;
  },
});
