// Auto-generated by @suite/generator. Do not edit.
// Sourced from operation: ListDocumentSignatoriesController_run (GET /case-files/{caseFileId}/signature-requests/{requestId}/documents/{documentId}/signatories)

import { defineTool } from "../core/index.js";
import { z } from "zod";
import { createClient, createConfig } from "../api/client/index.js";
import { listDocumentSignatoriesControllerRun } from "../api/sdk.gen.js";
import { zListDocumentSignatoriesControllerRunPath } from "../api/zod.gen.js";
import { zListDocumentSignatoriesControllerRunQuery } from "../api/zod.gen.js";
const inputSchema = z.object({
  ...zListDocumentSignatoriesControllerRunPath.shape,
  ...zListDocumentSignatoriesControllerRunQuery.shape,
});

export const signature_document_list = defineTool({
  name: "signature_document_list",
  description: "Lists documents in a signature request with their signing status per document. Requires: signature_request_create → requestId, case_file_create → caseFileId. IMPORTANT: when called with documentId it returns participant signing status (PENDING = not yet signed), NOT document processing status. To check if documents reached READY_TO_SIGN (required before activate_signature_request), use signature_request_get instead. Post-activation: poll until document status === SIGNED before calling signature_certificate_get.",
  inputSchema,
  annotations: {
    title: "Signature Document List",
    readOnlyHint: true,
    destructiveHint: false,
    idempotentHint: true,
    openWorldHint: false,
  },
  pollable: false,
  idempotencyWindowSeconds: 60,
  async execute(input, ctx) {
    const token = ctx.auth?.token ?? "";
    const sdkClient = createClient(
      createConfig({
        baseUrl: process.env.MCP_API_BASE_URL ?? "https://api-eadcustody.eadtrust.gocertius.io",
        headers: {
          Authorization: `Bearer ${token}`,
          ...(ctx.correlationId ? { "X-Correlation-Id": ctx.correlationId } : {}),
        },
      }),
    );

    // biome-ignore lint/suspicious/noExplicitAny: generated SDK call — input shape validated above
    const inp = input as any;
    // biome-ignore lint/suspicious/noExplicitAny: generated SDK function — types validated at generation time
    const sdkFn = listDocumentSignatoriesControllerRun as (opts: any) => Promise<any>;
    const response = await sdkFn({
      client: sdkClient,
      path: zListDocumentSignatoriesControllerRunPath.parse(inp),
      query: zListDocumentSignatoriesControllerRunQuery.parse(inp),
    });

    if (response.error !== undefined) {
      const msg = typeof response.error === "object" && response.error !== null && "message" in response.error
        ? String(response.error.message)
        : JSON.stringify(response.error);
      throw new Error(msg);
    }
    return response.data;
  },
});
