// Auto-generated by @suite/generator. Do not edit.
// Sourced from operation: CreateSignatureRequestController_run (POST /case-files/{caseFileId}/signature-requests)

import { defineTool } from "../core/index.js";
import { z } from "zod";
import { createClient, createConfig } from "../api/client/index.js";
import { createSignatureRequestControllerRun } from "../api/sdk.gen.js";
import { zCreateSignatureRequestControllerRunPath } from "../api/zod.gen.js";
import { zCreateSignatureRequestControllerRunBody } from "../api/zod.gen.js";
const inputSchema = z.object({
  ...zCreateSignatureRequestControllerRunPath.shape,
  ...zCreateSignatureRequestControllerRunBody.shape,
});

export const signature_request_create = defineTool({
  name: "signature_request_create",
  description:
    "Create a new signature request (envelope) in DRAFT status. Returns immediately with the request ID. " +
    "After creating, you must: (1) add documents via signature_request_add_document, " +
    "(2) upload each document binary to its S3 URL (PUT, application/octet-stream, no auth headers), " +
    "(3) wait for documents to reach READY_TO_SIGN status via signature_document_list, " +
    "(4) add signatories via signature_participant_create, " +
    "(5) set signature box positions via signature_coordinate_set (INTERPOSITION type only), " +
    "(6) activate via activate_signature_request. " +
    "To handle the entire flow in a single call (recommended), use signature_request_full_create instead.",
  inputSchema,
  annotations: {
    destructive: false,
    idempotent: false,
    requiresUserConfirmation: false,
  },
  pollable: false,
  idempotencyWindowSeconds: 86400,
  async execute(input, ctx) {
    const token = ctx.auth?.token ?? "";
    const sdkClient = createClient(
      createConfig({
        baseUrl: process.env.MCP_API_BASE_URL ?? "",
        headers: {
          Authorization: `Bearer ${token}`,
          ...(ctx.correlationId ? { "X-Correlation-Id": ctx.correlationId } : {}),
        },
      }),
    );

    // biome-ignore lint/suspicious/noExplicitAny: generated SDK call — input shape validated above
    const inp = input as any;
    // biome-ignore lint/suspicious/noExplicitAny: generated SDK function — types validated at generation time
    const sdkFn = createSignatureRequestControllerRun as (opts: any) => Promise<any>;
    const response = await sdkFn({
      client: sdkClient,
      path: zCreateSignatureRequestControllerRunPath.parse(inp),
      body: zCreateSignatureRequestControllerRunBody.parse(inp),
    });

    if (response.error !== undefined) {
      const msg = typeof response.error === "object" && response.error !== null && "message" in response.error
        ? String(response.error.message)
        : JSON.stringify(response.error);
      throw new Error(msg);
    }
    return response.data;
  },
});
