// Auto-generated by @suite/generator. Do not edit.
// Sourced from operation: ListDocumentObserversController_run (GET /case-files/{caseFileId}/signature-requests/{requestId}/documents/{documentId}/observers)

import { defineTool, UpstreamHttpError } from "../core/index.js";
import { z } from "zod";
import { createClient, createConfig } from "../api/client/index.js";
import { listDocumentObserversControllerRun } from "../api/sdk.gen.js";
import { zListDocumentObserversControllerRunPath } from "../api/zod.gen.js";
import { zListDocumentObserversControllerRunQuery } from "../api/zod.gen.js";
const rawInputSchema = z.object({
  ...zListDocumentObserversControllerRunPath.shape,
  ...zListDocumentObserversControllerRunQuery.shape,
});
// Story 6.5 (FR-27/P-A5): fills in descriptions for commonly reused field names
// (e.g. caseFileId) that Hey API's generated schema doesn't carry on its own.
const inputSchema = rawInputSchema;

export const signature_participant_list = defineTool({
  name: "signature_participant_list",
  description: "Lists all participants of a signature request. Requires: signature_request_create → requestId, case_file_create → caseFileId. Returns roles, contact details, and signing status.",
  inputSchema,
  annotations: {
    title: "Signature Participant List",
    readOnlyHint: true,
    destructiveHint: false,
    idempotentHint: true,
    openWorldHint: false,
  },
  pollable: false,
  idempotencyWindowSeconds: 60,
  async execute(input, ctx) {
    const token = ctx.auth?.token ?? "";
    const sdkClient = createClient(
      createConfig({
        baseUrl: process.env.MCP_API_BASE_URL ?? "https://api-eadcustody.eadtrust.gocertius.io",
        headers: {
          Authorization: `Bearer ${token}`,
          ...(ctx.correlationId ? { "X-Correlation-Id": ctx.correlationId } : {}),
        },
      }),
    );

    // biome-ignore lint/suspicious/noExplicitAny: generated SDK call — input shape validated above
    const inp = input as any;
    // biome-ignore lint/suspicious/noExplicitAny: generated SDK function — types validated at generation time
    const sdkFn = listDocumentObserversControllerRun as (opts: any) => Promise<any>;
    const response = await sdkFn({
      client: sdkClient,
      path: zListDocumentObserversControllerRunPath.parse(inp),
      query: zListDocumentObserversControllerRunQuery.parse(inp),
    });

    if (response.error !== undefined) {
      // Story 10.2: constructs a status-aware UpstreamHttpError instead of a plain
      // Error — mapUpstreamError's 422 field-hint / 5xx transient-retry branches can
      // only be reached this way; a plain Error always fell through to the generic
      // "transient failure" text, discarding the real HTTP status/detail. Uses
      // fromParsedError (not fromResponse) because @hey-api/client-fetch has already
      // consumed response.response's body to populate response.error by this point.
      throw UpstreamHttpError.fromParsedError(response.response?.status ?? 0, response.error, "signature_participant_list");
    }
    return response.data;
  },
});
