// Auto-generated by @suite/generator. Do not edit.
// Sourced from operation: ListUseCasesController_run (GET /companies/{companyId}/use-cases)

import { defineTool } from "../core/index.js";
import { z } from "zod";
import { createClient, createConfig } from "../api/client/index.js";
import { listUseCasesControllerRun } from "../api/sdk.gen.js";
import { zListUseCasesControllerRunPath } from "../api/zod.gen.js";
import { zListUseCasesControllerRunQuery } from "../api/zod.gen.js";
const inputSchema = z.object({
  ...zListUseCasesControllerRunPath.shape,
  ...zListUseCasesControllerRunQuery.shape,
});

export const use_case_list = defineTool({
  name: "use_case_list",
  description: "Lists available use cases for the account. Use cases define the allowed signature workflows and document types. Returns useCaseId values needed for signature_request_create.",
  inputSchema,
  annotations: {
    destructive: false,
    idempotent: true,
    requiresUserConfirmation: false,
  },
  pollable: false,
  idempotencyWindowSeconds: 60,
  async execute(input, ctx) {
    const token = ctx.auth?.token ?? "";
    const sdkClient = createClient(
      createConfig({
        baseUrl: process.env.MCP_API_BASE_URL ?? "",
        headers: {
          Authorization: `Bearer ${token}`,
          ...(ctx.correlationId ? { "X-Correlation-Id": ctx.correlationId } : {}),
        },
      }),
    );

    // biome-ignore lint/suspicious/noExplicitAny: generated SDK call — input shape validated above
    const inp = input as any;
    // biome-ignore lint/suspicious/noExplicitAny: generated SDK function — types validated at generation time
    const sdkFn = listUseCasesControllerRun as (opts: any) => Promise<any>;
    const response = await sdkFn({
      client: sdkClient,
      path: zListUseCasesControllerRunPath.parse(inp),
      query: zListUseCasesControllerRunQuery.parse(inp),
    });

    if (response.error !== undefined) {
      const msg = typeof response.error === "object" && response.error !== null && "message" in response.error
        ? String(response.error.message)
        : JSON.stringify(response.error);
      throw new Error(msg);
    }
    return response.data;
  },
});
